/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/user/Dropbox/projects/nim/stui/devtools/nimcache/colorchooser.o /home/user/Dropbox/projects/nim/stui/devtools/nimcache/colorchooser.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct tyTuple_47w2DboNEPf69aPgubZdd7Q tyTuple_47w2DboNEPf69aPgubZdd7Q;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU16 tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA;
typedef NU8 tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg;
typedef NU8 tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
typedef tyTuple_XOVT24GHXwqiEj5GCsEGCA tyArray_q6NkqhYAaVnMZpcgQ6A6Fg[140];
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyTuple_47w2DboNEPf69aPgubZdd7Q {
NI Field0;
NI Field1;
NI Field2;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_t9aT3T0WIRPdbbx6fet5NFg_40)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, TM_t9aT3T0WIRPdbbx6fet5NFg_43)(void);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwterminal)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQterminal)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, enableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w)(void);
static N_NIMCALL(void, TM_t9aT3T0WIRPdbbx6fet5NFg_190)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyTuple_47w2DboNEPf69aPgubZdd7Q, extractRGB_BBeGhczeu0Oe9b4tbckVIHA)(NI a);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, alignLeft_i9aDpuCfgBy0NVrlXlv36bA)(NimStringDesc* s, NI count, NIM_CHAR padding);
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_termiosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_colors256Init000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_colors256DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, colorchooserDatInit000)(void);
tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA c256_t3Skv9aGprfgz0k9aod8RJlg;
tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg c8fg_86DAbigYM4XuHYC6W1b9cVw;
tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA c8bg_k8W7dqPGu0MV3sD3rfkHyw;
NI i_l6c7c9ceQppA8VBDVk89cSkA;
extern TNimType NTI_1AotDP7Jyl8LczrTQSu0yA_;
extern TNimType NTI_ez9ah4IgQc0AbdW68acioDg_;
extern TNimType NTI_7jPyx0xRLWzxER9cSeCOA9bA_;
NimStringDesc* str_zFlrYcj9azqnpjDKL3LH48g;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
tyArray_q6NkqhYAaVnMZpcgQ6A6Fg colorNamesRGB_PFK7kNAHuAwiUTiqFKl9apQ;
extern TNimType NTI_XOVT24GHXwqiEj5GCsEGCA_;
TNimType NTI_q6NkqhYAaVnMZpcgQ6A6Fg_;
NI r_VQUa3ZOi7m9cDLo7vADMHkw;
NI g_0gQ9an9aH6OLZX8cjaUXA2Rg;
NI b_T9cOwUjyn72i6fEiJVKRfgw;
tyTuple_XOVT24GHXwqiEj5GCsEGCA col_otMHf44ehtHY19bTIoYpmGA;
tyTuple_47w2DboNEPf69aPgubZdd7Q __uvrD9coLKfWHbB9alJbrkmng;
extern TNimType NTI_47w2DboNEPf69aPgubZdd7Q_;
NI w_u9aZxU721yp3YSjgKVLEO8g;
NI i_l6c7c9ceQppA8VBDVk89cSkA_2;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_3, "\012\012FG 256 COLORS [38;5;<col#>m [48;5;<col#>m  ******************"
"******************\012", 82);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_2 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_3)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_4, "\033[38;5;", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_5, "m \342\226\210\342\226\210\342\226\210 ", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_6, "\033[0m ", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_12, "\012", 1);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_11 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_12)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_13, "\033[48;5;15m", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_19, "\012\012FG COLORS [<col#>m ******************************************"
"**********\012", 74);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_18 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_19)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_20, "\033[", 2);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_23, "\012\012BRIGHT FG COLORS [<col#>;1m ================================="
"=========================\012", 89);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_22 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_23)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_24, ";1m \342\226\210\342\226\210\342\226\210 ", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_27, "\012\012BG COLORS [<col#>m ******************************************"
"**********\012", 74);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_26 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_27)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_28, "m     ", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_31, "\012\012BRIGHT BG COLORS [<col#>;1m *********************************"
"*******************\012", 83);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_30 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_31)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_32, ";1m     ", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_35, "\012\012TRUECOLOR [38;2;<r#>;<g#>;<b#>m [48;2;<r#>;<g#>;<b#>m ......."
".................\012", 81);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_34 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_35)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_37, "\033[38;2;255;100;0mTRUECOLOR\033[0m\012", 31);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_36 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_37)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_39, "\033[48;2;255;100;0mTRUECOLOR\033[0m\012", 31);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_38 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_39)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_41, "COLORTERM", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_42, "", 0);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_45, "aliceblue", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_46, "antiquewhite", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_47, "aqua", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_48, "aquamarine", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_49, "azure", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_50, "beige", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_51, "bisque", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_52, "black", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_53, "blanchedalmond", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_54, "blue", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_55, "blueviolet", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_56, "brown", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_57, "burlywood", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_58, "cadetblue", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_59, "chartreuse", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_60, "chocolate", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_61, "coral", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_62, "cornflowerblue", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_63, "cornsilk", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_64, "crimson", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_65, "cyan", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_66, "darkblue", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_67, "darkcyan", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_68, "darkgoldenrod", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_69, "darkgray", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_70, "darkgreen", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_71, "darkkhaki", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_72, "darkmagenta", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_73, "darkolivegreen", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_74, "darkorange", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_75, "darkorchid", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_76, "darkred", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_77, "darksalmon", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_78, "darkseagreen", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_79, "darkslateblue", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_80, "darkslategray", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_81, "darkturquoise", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_82, "darkviolet", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_83, "deeppink", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_84, "deepskyblue", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_85, "dimgray", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_86, "dodgerblue", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_87, "firebrick", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_88, "floralwhite", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_89, "forestgreen", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_90, "fuchsia", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_91, "gainsboro", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_92, "ghostwhite", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_93, "gold", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_94, "goldenrod", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_95, "gray", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_96, "green", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_97, "greenyellow", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_98, "honeydew", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_99, "hotpink", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_100, "indianred", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_101, "indigo", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_102, "ivory", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_103, "khaki", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_104, "lavender", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_105, "lavenderblush", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_106, "lawngreen", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_107, "lemonchiffon", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_108, "lightblue", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_109, "lightcoral", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_110, "lightcyan", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_111, "lightgoldenrodyellow", 20);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_112, "lightgrey", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_113, "lightgreen", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_114, "lightpink", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_115, "lightsalmon", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_116, "lightseagreen", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_117, "lightskyblue", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_118, "lightslategray", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_119, "lightsteelblue", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_120, "lightyellow", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_121, "lime", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_122, "limegreen", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_123, "linen", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_124, "magenta", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_125, "maroon", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_126, "mediumaquamarine", 16);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_127, "mediumblue", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_128, "mediumorchid", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_129, "mediumpurple", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_130, "mediumseagreen", 14);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_131, "mediumslateblue", 15);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_132, "mediumspringgreen", 17);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_133, "mediumturquoise", 15);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_134, "mediumvioletred", 15);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_135, "midnightblue", 12);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_136, "mintcream", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_137, "mistyrose", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_138, "moccasin", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_139, "navajowhite", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_140, "navy", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_141, "oldlace", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_142, "olive", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_143, "olivedrab", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_144, "orange", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_145, "orangered", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_146, "orchid", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_147, "palegoldenrod", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_148, "palegreen", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_149, "paleturquoise", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_150, "palevioletred", 13);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_151, "papayawhip", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_152, "peachpuff", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_153, "peru", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_154, "pink", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_155, "plum", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_156, "powderblue", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_157, "purple", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_158, "red", 3);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_159, "rosybrown", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_160, "royalblue", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_161, "saddlebrown", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_162, "salmon", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_163, "sandybrown", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_164, "seagreen", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_165, "seashell", 8);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_166, "sienna", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_167, "silver", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_168, "skyblue", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_169, "slateblue", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_170, "slategray", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_171, "snow", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_172, "springgreen", 11);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_173, "steelblue", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_174, "tan", 3);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_175, "teal", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_176, "thistle", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_177, "tomato", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_178, "turquoise", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_179, "violet", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_180, "wheat", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_181, "white", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_182, "whitesmoke", 10);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_183, "yellow", 6);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_184, "yellowgreen", 11);
NIM_CONST tyArray_q6NkqhYAaVnMZpcgQ6A6Fg TM_t9aT3T0WIRPdbbx6fet5NFg_44 = {{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_45),
((NI) 15792383)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_46),
((NI) 16444375)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_47),
((NI) 65535)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_48),
((NI) 8388564)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_49),
((NI) 15794175)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_50),
((NI) 16119260)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_51),
((NI) 16770244)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_52),
((NI) 0)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_53),
((NI) 16772045)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_54),
((NI) 255)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_55),
((NI) 9055202)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_56),
((NI) 10824234)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_57),
((NI) 14596231)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_58),
((NI) 6266528)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_59),
((NI) 8388352)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_60),
((NI) 13789470)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_61),
((NI) 16744272)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_62),
((NI) 6591981)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_63),
((NI) 16775388)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_64),
((NI) 14423100)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_65),
((NI) 65535)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_66),
((NI) 139)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_67),
((NI) 35723)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_68),
((NI) 12092939)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_69),
((NI) 11119017)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_70),
((NI) 25600)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_71),
((NI) 12433259)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_72),
((NI) 9109643)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_73),
((NI) 5597999)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_74),
((NI) 16747520)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_75),
((NI) 10040012)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_76),
((NI) 9109504)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_77),
((NI) 15308410)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_78),
((NI) 9419919)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_79),
((NI) 4734347)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_80),
((NI) 3100495)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_81),
((NI) 52945)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_82),
((NI) 9699539)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_83),
((NI) 16716947)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_84),
((NI) 49151)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_85),
((NI) 6908265)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_86),
((NI) 2003199)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_87),
((NI) 11674146)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_88),
((NI) 16775920)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_89),
((NI) 2263842)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_90),
((NI) 16711935)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_91),
((NI) 14474460)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_92),
((NI) 16316671)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_93),
((NI) 16766720)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_94),
((NI) 14329120)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_95),
((NI) 8421504)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_96),
((NI) 32768)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_97),
((NI) 11403055)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_98),
((NI) 15794160)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_99),
((NI) 16738740)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_100),
((NI) 13458524)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_101),
((NI) 4915330)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_102),
((NI) 16777200)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_103),
((NI) 15787660)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_104),
((NI) 15132410)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_105),
((NI) 16773365)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_106),
((NI) 8190976)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_107),
((NI) 16775885)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_108),
((NI) 11393254)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_109),
((NI) 15761536)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_110),
((NI) 14745599)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_111),
((NI) 16448210)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_112),
((NI) 13882323)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_113),
((NI) 9498256)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_114),
((NI) 16758465)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_115),
((NI) 16752762)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_116),
((NI) 2142890)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_117),
((NI) 8900346)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_118),
((NI) 7833753)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_119),
((NI) 11584734)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_120),
((NI) 16777184)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_121),
((NI) 65280)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_122),
((NI) 3329330)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_123),
((NI) 16445670)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_124),
((NI) 16711935)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_125),
((NI) 8388608)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_126),
((NI) 6737322)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_127),
((NI) 205)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_128),
((NI) 12211667)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_129),
((NI) 9662680)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_130),
((NI) 3978097)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_131),
((NI) 8087790)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_132),
((NI) 64154)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_133),
((NI) 4772300)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_134),
((NI) 13047173)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_135),
((NI) 1644912)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_136),
((NI) 16121850)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_137),
((NI) 16770273)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_138),
((NI) 16770229)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_139),
((NI) 16768685)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_140),
((NI) 128)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_141),
((NI) 16643558)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_142),
((NI) 8421376)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_143),
((NI) 7048739)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_144),
((NI) 16753920)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_145),
((NI) 16729344)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_146),
((NI) 14315734)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_147),
((NI) 15657130)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_148),
((NI) 10025880)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_149),
((NI) 11529966)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_150),
((NI) 14184595)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_151),
((NI) 16773077)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_152),
((NI) 16767673)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_153),
((NI) 13468991)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_154),
((NI) 16761035)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_155),
((NI) 14524637)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_156),
((NI) 11591910)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_157),
((NI) 8388736)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_158),
((NI) 16711680)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_159),
((NI) 12357519)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_160),
((NI) 4286945)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_161),
((NI) 9127187)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_162),
((NI) 16416882)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_163),
((NI) 16032864)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_164),
((NI) 3050327)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_165),
((NI) 16774638)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_166),
((NI) 10506797)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_167),
((NI) 12632256)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_168),
((NI) 8900331)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_169),
((NI) 6970061)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_170),
((NI) 7372944)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_171),
((NI) 16775930)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_172),
((NI) 65407)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_173),
((NI) 4620980)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_174),
((NI) 13808780)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_175),
((NI) 32896)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_176),
((NI) 14204888)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_177),
((NI) 16737095)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_178),
((NI) 4251856)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_179),
((NI) 15631086)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_180),
((NI) 16113331)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_181),
((NI) 16777215)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_182),
((NI) 16119285)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_183),
((NI) 16776960)}
,
{((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_184),
((NI) 10145074)}
}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_188, "truecolor", 9);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_189, "24bit", 5);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_t9aT3T0WIRPdbbx6fet5NFg_187 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_188),
((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_189)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_191, "\033[0m", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_192, "\033[38;2;0;0;0m\033[48;2;", 20);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_193, ";", 1);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_194, "m", 1);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_195, "    ", 4);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_196, "\033[38;2;", 7);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_197, "\033[0m\012", 5);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_200, "\033[1mBold: \\u001b[1m \033[0m", 24);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_199 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_200)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_202, "\033[4mUnderline: \\u001b[4m \033[0m", 29);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_201 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_202)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_204, "\033[7mReversed: \\u001b[7m \033[0m", 28);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_203 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_204)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_206, "\033[5mBlink: \\u001b[5m \033[0m", 25);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_205 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_206)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_208, "\033[3mStandout: \\u001b[3m \033[0m", 28);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_207 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_208)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_210, "\033[2mDIM: \\u001b[2m \033[0m", 23);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_209 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_210)}
;
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_212, "m This is a test ", 17);
STRING_LITERAL(TM_t9aT3T0WIRPdbbx6fet5NFg_213, "\033[0m      ", 10);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_t9aT3T0WIRPdbbx6fet5NFg_215 = {((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_191)}
;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, TM_t9aT3T0WIRPdbbx6fet5NFg_40)(void) {
	nimGCvisit((void*)str_zFlrYcj9azqnpjDKL3LH48g, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, TM_t9aT3T0WIRPdbbx6fet5NFg_43)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 140; T1_++) {
	nimGCvisit((void*)colorNamesRGB_PFK7kNAHuAwiUTiqFKl9apQ[T1_].Field0, 0);
	}
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQterminal)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_t9aT3T0WIRPdbbx6fet5NFg_185;
				NI TM_t9aT3T0WIRPdbbx6fet5NFg_186;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_t9aT3T0WIRPdbbx6fet5NFg_185 = addInt(result, ((NI) 1));
				result = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_185);
				nimln_(2188, "system.nim");
				TM_t9aT3T0WIRPdbbx6fet5NFg_186 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_186);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwterminal)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQterminal(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_t9aT3T0WIRPdbbx6fet5NFg_190)(void) {
	nimGCvisit((void*)col_otMHf44ehtHY19bTIoYpmGA.Field0, 0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_strformatDatInit000();
	stdlib_colorsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_posixDatInit000();
	stdlib_termiosDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_terminalDatInit000();
	unknown_colors256DatInit000();
	stdlib_strtabsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_linuxDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_osprocDatInit000();
	colorchooserDatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_unicodeInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_strformatInit000();
	stdlib_colorsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_posixInit000();
	stdlib_termiosInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_terminalInit000();
	unknown_colors256Init000();
	stdlib_strtabsInit000();
	stdlib_streamsInit000();
	stdlib_linuxInit000();
	stdlib_cpuinfoInit000();
	stdlib_osprocInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("colorchooser", "colorchooser.nim");
nimRegisterGlobalMarker(TM_t9aT3T0WIRPdbbx6fet5NFg_40);
nimRegisterGlobalMarker(TM_t9aT3T0WIRPdbbx6fet5NFg_43);
nimRegisterGlobalMarker(TM_t9aT3T0WIRPdbbx6fet5NFg_190);
	nimln_(5, "colorchooser.nim");
	c8fg_86DAbigYM4XuHYC6W1b9cVw = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 32);
	nimln_(6, "colorchooser.nim");
	c8bg_k8W7dqPGu0MV3sD3rfkHyw = ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA) 40);
	nimln_(10, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_2, 1);
	{
		nimln_(12, "colorchooser.nim");
		while (1) {
			NimStringDesc* T3_;
			NimStringDesc* T4_;
			NimStringDesc* T5_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_7;
			NimStringDesc* T6_;
			NimStringDesc* T7_;
			NimStringDesc* T8_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_8;
			NimStringDesc* T9_;
			NimStringDesc* T10_;
			NimStringDesc* T11_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_9;
			NimStringDesc* T12_;
			NimStringDesc* T13_;
			NimStringDesc* T14_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_10;
			if (!(i_l6c7c9ceQppA8VBDVk89cSkA < ((NI) 256))) goto LA2;
			nimln_(13, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(14, "colorchooser.nim");
			T3_ = (NimStringDesc*)0;
			T4_ = (NimStringDesc*)0;
			T4_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T5_ = (NimStringDesc*)0;
			T5_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T3_ = rawNewString(T4_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T5_->Sup.len + 24);
appendString(T3_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T3_, T4_);
appendString(T3_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T3_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T3_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T3_, T5_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T3_);
			nimln_(15, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_7 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_7);
			nimln_(16, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(17, "colorchooser.nim");
			T6_ = (NimStringDesc*)0;
			T7_ = (NimStringDesc*)0;
			T7_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T8_ = (NimStringDesc*)0;
			T8_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T6_ = rawNewString(T7_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T8_->Sup.len + 24);
appendString(T6_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T6_, T7_);
appendString(T6_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T6_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T6_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T6_, T8_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T6_);
			nimln_(18, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_8 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_8);
			nimln_(20, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(21, "colorchooser.nim");
			T9_ = (NimStringDesc*)0;
			T10_ = (NimStringDesc*)0;
			T10_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T11_ = (NimStringDesc*)0;
			T11_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T9_ = rawNewString(T10_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T11_->Sup.len + 24);
appendString(T9_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T9_, T10_);
appendString(T9_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T9_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T9_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T9_, T11_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T9_);
			nimln_(22, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_9 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_9);
			nimln_(23, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(24, "colorchooser.nim");
			T12_ = (NimStringDesc*)0;
			T13_ = (NimStringDesc*)0;
			T13_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T14_ = (NimStringDesc*)0;
			T14_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T12_ = rawNewString(T13_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T14_->Sup.len + 24);
appendString(T12_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T12_, T13_);
appendString(T12_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T12_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T12_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T12_, T14_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T12_);
			nimln_(25, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_10 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_10);
			nimln_(27, "colorchooser.nim");
			echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_11, 1);
		} LA2: ;
	}
	{
		nimln_(29, "colorchooser.nim");
		while (1) {
			NimStringDesc* T17_;
			NimStringDesc* T18_;
			NimStringDesc* T19_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_14;
			NimStringDesc* T20_;
			NimStringDesc* T21_;
			NimStringDesc* T22_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_15;
			NimStringDesc* T23_;
			NimStringDesc* T24_;
			NimStringDesc* T25_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_16;
			NimStringDesc* T26_;
			NimStringDesc* T27_;
			NimStringDesc* T28_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_17;
			if (!(i_l6c7c9ceQppA8VBDVk89cSkA < ((NI) 256))) goto LA16;
			nimln_(30, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(31, "colorchooser.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_13));
			nimln_(32, "colorchooser.nim");
			T17_ = (NimStringDesc*)0;
			T18_ = (NimStringDesc*)0;
			T18_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T19_ = (NimStringDesc*)0;
			T19_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T17_ = rawNewString(T18_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T19_->Sup.len + 24);
appendString(T17_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T17_, T18_);
appendString(T17_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T17_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T17_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T17_, T19_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T17_);
			nimln_(33, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_14 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_14);
			nimln_(34, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(35, "colorchooser.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_13));
			nimln_(36, "colorchooser.nim");
			T20_ = (NimStringDesc*)0;
			T21_ = (NimStringDesc*)0;
			T21_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T22_ = (NimStringDesc*)0;
			T22_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T20_ = rawNewString(T21_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T22_->Sup.len + 24);
appendString(T20_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T20_, T21_);
appendString(T20_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T20_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T20_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T20_, T22_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T20_);
			nimln_(37, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_15 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_15);
			nimln_(39, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(40, "colorchooser.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_13));
			nimln_(41, "colorchooser.nim");
			T23_ = (NimStringDesc*)0;
			T24_ = (NimStringDesc*)0;
			T24_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T25_ = (NimStringDesc*)0;
			T25_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T23_ = rawNewString(T24_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T25_->Sup.len + 24);
appendString(T23_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T23_, T24_);
appendString(T23_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T23_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T23_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T23_, T25_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T23_);
			nimln_(42, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_16 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_16);
			nimln_(43, "colorchooser.nim");
			c256_t3Skv9aGprfgz0k9aod8RJlg = ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 0), ((tyEnum_Color256_1AotDP7Jyl8LczrTQSu0yA) 255)));
			nimln_(44, "colorchooser.nim");
			write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_13));
			nimln_(45, "colorchooser.nim");
			T26_ = (NimStringDesc*)0;
			T27_ = (NimStringDesc*)0;
			T27_ = nimIntToStr(((NI) (c256_t3Skv9aGprfgz0k9aod8RJlg)));
			T28_ = (NimStringDesc*)0;
			T28_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T26_ = rawNewString(T27_->Sup.len + reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_))->Sup.len + T28_->Sup.len + 24);
appendString(T26_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_4));
appendString(T26_, T27_);
appendString(T26_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T26_, reprEnum((NI)c256_t3Skv9aGprfgz0k9aod8RJlg, (&NTI_1AotDP7Jyl8LczrTQSu0yA_)));
appendString(T26_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T26_, T28_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T26_);
			nimln_(46, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_17 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_17);
			nimln_(48, "colorchooser.nim");
			echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_11, 1);
		} LA16: ;
	}
	nimln_(51, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_18, 1);
	nimln_(52, "colorchooser.nim");
	i_l6c7c9ceQppA8VBDVk89cSkA = ((NI) 30);
	{
		nimln_(53, "colorchooser.nim");
		while (1) {
			NimStringDesc* T31_;
			NimStringDesc* T32_;
			NimStringDesc* T33_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_21;
			if (!(i_l6c7c9ceQppA8VBDVk89cSkA < ((NI) 38))) goto LA30;
			nimln_(54, "colorchooser.nim");
			c8fg_86DAbigYM4XuHYC6W1b9cVw = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 30), ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 37)));
			nimln_(55, "colorchooser.nim");
			T31_ = (NimStringDesc*)0;
			T32_ = (NimStringDesc*)0;
			T32_ = nimIntToStr(((NI) (c8fg_86DAbigYM4XuHYC6W1b9cVw)));
			T33_ = (NimStringDesc*)0;
			T33_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T31_ = rawNewString(T32_->Sup.len + reprEnum((NI)c8fg_86DAbigYM4XuHYC6W1b9cVw, (&NTI_ez9ah4IgQc0AbdW68acioDg_))->Sup.len + T33_->Sup.len + 19);
appendString(T31_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_20));
appendString(T31_, T32_);
appendString(T31_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_5));
appendString(T31_, reprEnum((NI)c8fg_86DAbigYM4XuHYC6W1b9cVw, (&NTI_ez9ah4IgQc0AbdW68acioDg_)));
appendString(T31_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T31_, T33_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T31_);
			nimln_(56, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_21 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_21);
		} LA30: ;
	}
	nimln_(58, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_22, 1);
	nimln_(59, "colorchooser.nim");
	i_l6c7c9ceQppA8VBDVk89cSkA = ((NI) 30);
	{
		nimln_(60, "colorchooser.nim");
		while (1) {
			NimStringDesc* T36_;
			NimStringDesc* T37_;
			NimStringDesc* T38_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_25;
			if (!(i_l6c7c9ceQppA8VBDVk89cSkA < ((NI) 38))) goto LA35;
			nimln_(61, "colorchooser.nim");
			c8fg_86DAbigYM4XuHYC6W1b9cVw = ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 30), ((tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg) 37)));
			nimln_(62, "colorchooser.nim");
			T36_ = (NimStringDesc*)0;
			T37_ = (NimStringDesc*)0;
			T37_ = nimIntToStr(((NI) (c8fg_86DAbigYM4XuHYC6W1b9cVw)));
			T38_ = (NimStringDesc*)0;
			T38_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T36_ = rawNewString(T37_->Sup.len + reprEnum((NI)c8fg_86DAbigYM4XuHYC6W1b9cVw, (&NTI_ez9ah4IgQc0AbdW68acioDg_))->Sup.len + T38_->Sup.len + 21);
appendString(T36_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_20));
appendString(T36_, T37_);
appendString(T36_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_24));
appendString(T36_, reprEnum((NI)c8fg_86DAbigYM4XuHYC6W1b9cVw, (&NTI_ez9ah4IgQc0AbdW68acioDg_)));
appendString(T36_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T36_, T38_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T36_);
			nimln_(63, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_25 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_25);
		} LA35: ;
	}
	nimln_(65, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_26, 1);
	nimln_(66, "colorchooser.nim");
	i_l6c7c9ceQppA8VBDVk89cSkA = ((NI) 40);
	{
		nimln_(67, "colorchooser.nim");
		while (1) {
			NimStringDesc* T41_;
			NimStringDesc* T42_;
			NimStringDesc* T43_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_29;
			if (!(i_l6c7c9ceQppA8VBDVk89cSkA < ((NI) 48))) goto LA40;
			nimln_(68, "colorchooser.nim");
			c8bg_k8W7dqPGu0MV3sD3rfkHyw = ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA) 40), ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA) 47)));
			nimln_(69, "colorchooser.nim");
			T41_ = (NimStringDesc*)0;
			T42_ = (NimStringDesc*)0;
			T42_ = nimIntToStr(((NI) (c8bg_k8W7dqPGu0MV3sD3rfkHyw)));
			T43_ = (NimStringDesc*)0;
			T43_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T41_ = rawNewString(T42_->Sup.len + reprEnum((NI)c8bg_k8W7dqPGu0MV3sD3rfkHyw, (&NTI_7jPyx0xRLWzxER9cSeCOA9bA_))->Sup.len + T43_->Sup.len + 13);
appendString(T41_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_20));
appendString(T41_, T42_);
appendString(T41_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_28));
appendString(T41_, reprEnum((NI)c8bg_k8W7dqPGu0MV3sD3rfkHyw, (&NTI_7jPyx0xRLWzxER9cSeCOA9bA_)));
appendString(T41_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T41_, T43_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T41_);
			nimln_(70, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_29 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_29);
		} LA40: ;
	}
	nimln_(72, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_30, 1);
	nimln_(73, "colorchooser.nim");
	i_l6c7c9ceQppA8VBDVk89cSkA = ((NI) 40);
	{
		nimln_(74, "colorchooser.nim");
		while (1) {
			NimStringDesc* T46_;
			NimStringDesc* T47_;
			NimStringDesc* T48_;
			NI TM_t9aT3T0WIRPdbbx6fet5NFg_33;
			if (!(i_l6c7c9ceQppA8VBDVk89cSkA < ((NI) 48))) goto LA45;
			nimln_(75, "colorchooser.nim");
			c8bg_k8W7dqPGu0MV3sD3rfkHyw = ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA)chckRange(i_l6c7c9ceQppA8VBDVk89cSkA, ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA) 40), ((tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA) 47)));
			nimln_(76, "colorchooser.nim");
			T46_ = (NimStringDesc*)0;
			T47_ = (NimStringDesc*)0;
			T47_ = nimIntToStr(((NI) (c8bg_k8W7dqPGu0MV3sD3rfkHyw)));
			T48_ = (NimStringDesc*)0;
			T48_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA);
			T46_ = rawNewString(T47_->Sup.len + reprEnum((NI)c8bg_k8W7dqPGu0MV3sD3rfkHyw, (&NTI_7jPyx0xRLWzxER9cSeCOA9bA_))->Sup.len + T48_->Sup.len + 15);
appendString(T46_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_20));
appendString(T46_, T47_);
appendString(T46_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_32));
appendString(T46_, reprEnum((NI)c8bg_k8W7dqPGu0MV3sD3rfkHyw, (&NTI_7jPyx0xRLWzxER9cSeCOA9bA_)));
appendString(T46_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_6));
appendString(T46_, T48_);
			write_c4mGyJBvK73pdM22jiweKQ(stdout, T46_);
			nimln_(77, "colorchooser.nim");
			TM_t9aT3T0WIRPdbbx6fet5NFg_33 = addInt(i_l6c7c9ceQppA8VBDVk89cSkA, ((NI) 1));
			i_l6c7c9ceQppA8VBDVk89cSkA = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_33);
		} LA45: ;
	}
	nimln_(79, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_34, 1);
	nimln_(80, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_36, 1);
	nimln_(81, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_38, 1);
	nimln_(83, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_11, 1);
	nimln_(87, "colorchooser.nim");
	asgnRefNoCycle((void**) (&str_zFlrYcj9azqnpjDKL3LH48g), getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_41), ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_42)));
	nimln_(89, "colorchooser.nim");
	genericAssign((void*)colorNamesRGB_PFK7kNAHuAwiUTiqFKl9apQ, (void*)TM_t9aT3T0WIRPdbbx6fet5NFg_44, (&NTI_q6NkqhYAaVnMZpcgQ6A6Fg_));
	nimln_(231, "colorchooser.nim");
	resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg();
	nimln_(235, "colorchooser.nim");
	{
		NIM_BOOL T51_;
		T51_ = (NIM_BOOL)0;
		T51_ = contains_jPdUhZfr9a8sH2V3ZBDljzwterminal(TM_t9aT3T0WIRPdbbx6fet5NFg_187, 2, str_zFlrYcj9azqnpjDKL3LH48g);
		if (!T51_) goto LA52_;
		nimln_(236, "colorchooser.nim");
		enableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w();
		{
			NI i;
			nimln_(2199, "system.nim");
			i = ((NI) 0);
			nimln_(2200, "system.nim");
			{
				if (!(((NI) (i)) <= ((NI) 139))) goto LA57_;
				{
					nimln_(2201, "system.nim");
					while (1) {
						NimStringDesc* T61_;
						NimStringDesc* T62_;
						NimStringDesc* T63_;
						NimStringDesc* T64_;
						NimStringDesc* T65_;
						NimStringDesc* T66_;
						NimStringDesc* T67_;
						NimStringDesc* T68_;
						NimStringDesc* T69_;
						NimStringDesc* T70_;
						NimStringDesc* T71_;
						NimStringDesc* T72_;
						NimStringDesc* T73_;
						NI TM_t9aT3T0WIRPdbbx6fet5NFg_198;
						nimln_(2202, "system.nim");
						T61_ = (NimStringDesc*)0;
						T61_ = col_otMHf44ehtHY19bTIoYpmGA.Field0; col_otMHf44ehtHY19bTIoYpmGA.Field0 = copyStringRC1(colorNamesRGB_PFK7kNAHuAwiUTiqFKl9apQ[(i)- 0].Field0);
						if (T61_) nimGCunrefNoCycle(T61_);
						col_otMHf44ehtHY19bTIoYpmGA.Field1 = colorNamesRGB_PFK7kNAHuAwiUTiqFKl9apQ[(i)- 0].Field1;
						nimln_(249, "colorchooser.nim");
						write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_191));
						chckNil((void*)(&__uvrD9coLKfWHbB9alJbrkmng));
						genericReset((void*)(&__uvrD9coLKfWHbB9alJbrkmng), (&NTI_47w2DboNEPf69aPgubZdd7Q_));
						nimln_(250, "colorchooser.nim");
						__uvrD9coLKfWHbB9alJbrkmng = extractRGB_BBeGhczeu0Oe9b4tbckVIHA(col_otMHf44ehtHY19bTIoYpmGA.Field1);
						r_VQUa3ZOi7m9cDLo7vADMHkw = ((NI) (__uvrD9coLKfWHbB9alJbrkmng.Field0));
						g_0gQ9an9aH6OLZX8cjaUXA2Rg = ((NI) (__uvrD9coLKfWHbB9alJbrkmng.Field1));
						b_T9cOwUjyn72i6fEiJVKRfgw = ((NI) (__uvrD9coLKfWHbB9alJbrkmng.Field2));
						nimln_(251, "colorchooser.nim");
						T62_ = (NimStringDesc*)0;
						T63_ = (NimStringDesc*)0;
						T63_ = nimIntToStr(r_VQUa3ZOi7m9cDLo7vADMHkw);
						T64_ = (NimStringDesc*)0;
						T64_ = nimIntToStr(g_0gQ9an9aH6OLZX8cjaUXA2Rg);
						T65_ = (NimStringDesc*)0;
						T65_ = nimIntToStr(b_T9cOwUjyn72i6fEiJVKRfgw);
						T66_ = (NimStringDesc*)0;
						T66_ = rawNewString(col_otMHf44ehtHY19bTIoYpmGA.Field0->Sup.len + 4);
appendString(T66_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_195));
appendString(T66_, col_otMHf44ehtHY19bTIoYpmGA.Field0);
						T67_ = (NimStringDesc*)0;
						T67_ = alignLeft_i9aDpuCfgBy0NVrlXlv36bA(T66_, ((NI) 25), 32);
						T62_ = rawNewString(T63_->Sup.len + T64_->Sup.len + T65_->Sup.len + T67_->Sup.len + 27);
appendString(T62_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_192));
appendString(T62_, T63_);
appendString(T62_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_193));
appendString(T62_, T64_);
appendString(T62_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_193));
appendString(T62_, T65_);
appendString(T62_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_194));
appendString(T62_, T67_);
appendString(T62_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_191));
						write_c4mGyJBvK73pdM22jiweKQ(stdout, T62_);
						nimln_(252, "colorchooser.nim");
						T68_ = (NimStringDesc*)0;
						T69_ = (NimStringDesc*)0;
						T69_ = nimIntToStr(r_VQUa3ZOi7m9cDLo7vADMHkw);
						T70_ = (NimStringDesc*)0;
						T70_ = nimIntToStr(g_0gQ9an9aH6OLZX8cjaUXA2Rg);
						T71_ = (NimStringDesc*)0;
						T71_ = nimIntToStr(b_T9cOwUjyn72i6fEiJVKRfgw);
						T72_ = (NimStringDesc*)0;
						T72_ = rawNewString(col_otMHf44ehtHY19bTIoYpmGA.Field0->Sup.len + 4);
appendString(T72_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_195));
appendString(T72_, col_otMHf44ehtHY19bTIoYpmGA.Field0);
						T73_ = (NimStringDesc*)0;
						T73_ = alignLeft_i9aDpuCfgBy0NVrlXlv36bA(T72_, ((NI) 25), 32);
						T68_ = rawNewString(T69_->Sup.len + T70_->Sup.len + T71_->Sup.len + T73_->Sup.len + 15);
appendString(T68_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_196));
appendString(T68_, T69_);
appendString(T68_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_193));
appendString(T68_, T70_);
appendString(T68_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_193));
appendString(T68_, T71_);
appendString(T68_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_194));
appendString(T68_, T73_);
appendString(T68_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_197));
						write_c4mGyJBvK73pdM22jiweKQ(stdout, T68_);
						nimln_(254, "colorchooser.nim");
						write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_191));
						nimln_(255, "colorchooser.nim");
						write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_12));
						nimln_(2203, "system.nim");
						{
							if (!(((NI) 139) <= ((NI) (i)))) goto LA76_;
							goto LA59;
						}
						LA76_: ;
						nimln_(2204, "system.nim");
						TM_t9aT3T0WIRPdbbx6fet5NFg_198 = addInt(i, ((NI) 1));
						if (TM_t9aT3T0WIRPdbbx6fet5NFg_198 < 0 || TM_t9aT3T0WIRPdbbx6fet5NFg_198 > 139) raiseOverflow();
						i = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_198);
					}
				} LA59: ;
			}
			LA57_: ;
		}
	}
	LA52_: ;
	nimln_(258, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_199, 1);
	nimln_(259, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_201, 1);
	nimln_(260, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_203, 1);
	nimln_(262, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_205, 1);
	nimln_(263, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_207, 1);
	nimln_(264, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_209, 1);
	nimln_(266, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_11, 1);
	nimln_(267, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_11, 1);
	nimln_(269, "colorchooser.nim");
	w_u9aZxU721yp3YSjgKVLEO8g = terminalWidth_Tjr5MOdj42hdx5sjNUiDXw();
	{
		NI res;
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_t9aT3T0WIRPdbbx6fet5NFg_211;
				NimStringDesc* T85_;
				NimStringDesc* T86_;
				NimStringDesc* T87_;
				NI TM_t9aT3T0WIRPdbbx6fet5NFg_214;
				if (!(res <= ((NI) 55))) goto LA80;
				nimln_(2047, "system.nim");
				i_l6c7c9ceQppA8VBDVk89cSkA_2 = res;
				nimln_(271, "colorchooser.nim");
				TM_t9aT3T0WIRPdbbx6fet5NFg_211 = subInt(w_u9aZxU721yp3YSjgKVLEO8g, ((NI) 26));
				w_u9aZxU721yp3YSjgKVLEO8g = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_211);
				nimln_(272, "colorchooser.nim");
				{
					if (!(w_u9aZxU721yp3YSjgKVLEO8g < ((NI) 26))) goto LA83_;
					nimln_(273, "colorchooser.nim");
					write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_12));
					nimln_(274, "colorchooser.nim");
					w_u9aZxU721yp3YSjgKVLEO8g = terminalWidth_Tjr5MOdj42hdx5sjNUiDXw();
				}
				LA83_: ;
				nimln_(275, "colorchooser.nim");
				T85_ = (NimStringDesc*)0;
				T86_ = (NimStringDesc*)0;
				T86_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA_2);
				T87_ = (NimStringDesc*)0;
				T87_ = nimIntToStr(i_l6c7c9ceQppA8VBDVk89cSkA_2);
				T85_ = rawNewString(T86_->Sup.len + T87_->Sup.len + 29);
appendString(T85_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_20));
appendString(T85_, T86_);
appendString(T85_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_212));
appendString(T85_, T87_);
appendString(T85_, ((NimStringDesc*) &TM_t9aT3T0WIRPdbbx6fet5NFg_213));
				write_c4mGyJBvK73pdM22jiweKQ(stdout, T85_);
				nimln_(2048, "system.nim");
				TM_t9aT3T0WIRPdbbx6fet5NFg_214 = addInt(res, ((NI) 1));
				res = (NI)(TM_t9aT3T0WIRPdbbx6fet5NFg_214);
			} LA80: ;
		}
	}
	nimln_(327, "colorchooser.nim");
	echoBinSafe(TM_t9aT3T0WIRPdbbx6fet5NFg_215, 1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, colorchooserDatInit000)(void) {
NTI_q6NkqhYAaVnMZpcgQ6A6Fg_.size = sizeof(tyArray_q6NkqhYAaVnMZpcgQ6A6Fg);
NTI_q6NkqhYAaVnMZpcgQ6A6Fg_.kind = 16;
NTI_q6NkqhYAaVnMZpcgQ6A6Fg_.base = (&NTI_XOVT24GHXwqiEj5GCsEGCA_);
NTI_q6NkqhYAaVnMZpcgQ6A6Fg_.flags = 2;
}

