/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/user/Dropbox/projects/nim/stui/devtools/nimcache/stdlib_strtabs.o /home/user/Dropbox/projects/nim/stui/devtools/nimcache/stdlib_strtabs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw {
  RootObj Sup;
NI counter;
tySequence_4eQHGndY6XBYpFOH09apV8Q* data;
tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tySet_tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg;
typedef NU8 tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg;
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NI, nstlen)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, myhash_g4UMXDeIi4hi42WuIY9cM4A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_3)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NI, hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_2)(NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp_6dqTqYQ9cC63hkWdN9br54EA)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash_K02IbeDTRFZ9b4m0M4Kahlg)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet_g4UMXDeIi4hi42WuIY9cM4A_2)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, nstTake)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, mget_AtOx3IKEp1Smie6HNHB9buQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getOrDefault_sPC3Tb9bX9b1TxdHlL7x9cN3Q)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* default_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsthasKey)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_mzHkEOwMjp27RScMrhWA5A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_YkqIveHDR3SuLUhxpyZbuQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySequence_4eQHGndY6XBYpFOH09apV8Q** data, NimStringDesc* key, NimStringDesc* val);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_1rn449bBULy9cLwCWr7ISAqg)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val);
N_LIB_PRIVATE N_NIMCALL(void, raiseFormatException_UlRj9cCVaVq3wqa9ckfyqy9cQ)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getValue_mjQZRNgxAa33iqM216j4PQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySet_tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg flags, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTable)(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
static N_NIMCALL(void, Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw)(void* p, NI op);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, clear_mr5fULczKYTosYcaVX0A0g)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* s, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithPairs)(NimStringDesc** keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithTableConstr)(tyTuple_UV3llMMYFckfui8YMBuUZA* keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySet_tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg flags);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nstDollar)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_UV3llMMYFckfui8YMBuUZA_;
TNimType NTI_4eQHGndY6XBYpFOH09apV8Q_;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_;
TNimType NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_;
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_2, "\012counter < length ", 18);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_8, "key not found: ", 15);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_12, "format string: key not found: ", 30);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_13, "", 0);
NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw PatternChars_FgmryRoMjt9bXDR0LGn9c9bDw = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x87, 0xFE, 0xFF, 0xFF, 0x07,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
;
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_35, "{:}", 3);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_36, "{", 1);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_37, ", ", 2);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_38, ": ", 2);
STRING_LITERAL(TM_ZT9crccxweoChVXn9cHcxIXQ_40, "}", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, nstlen)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t) {
	NI result;
	nimfr_("len", "strtabs.nim");
	result = (NI)0;
	nimln_(46, "strtabs.nim");
	result = (*t).counter;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, myhash_g4UMXDeIi4hi42WuIY9cM4A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NI result;
	nimfr_("myhash", "strtabs.nim");
	result = (NI)0;
	nimln_(85, "strtabs.nim");
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		nimln_(86, "strtabs.nim");
		result = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		nimln_(87, "strtabs.nim");
		result = hashIgnoreCase_uBstFm5SYVQeOL3j9c9bc58A_3(key);
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		nimln_(88, "strtabs.nim");
		result = hashIgnoreStyle_uBstFm5SYVQeOL3j9c9bc58A_2(key);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, myCmp_6dqTqYQ9cC63hkWdN9br54EA)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	nimfr_("myCmp", "strtabs.nim");
	result = (NIM_BOOL)0;
	nimln_(91, "strtabs.nim");
	switch ((*t).mode) {
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 0):
	{
		NI T2_;
		nimln_(92, "strtabs.nim");
		T2_ = (NI)0;
		T2_ = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(a, b);
		result = (T2_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 1):
	{
		NI T4_;
		nimln_(93, "strtabs.nim");
		T4_ = (NI)0;
		T4_ = nsuCmpIgnoreCase(a, b);
		result = (T4_ == ((NI) 0));
	}
	break;
	case ((tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ) 2):
	{
		NI T6_;
		nimln_(94, "strtabs.nim");
		T6_ = (NI)0;
		T6_ = nsuCmpIgnoreStyle(a, b);
		result = (T6_ == ((NI) 0));
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, mustRehash_K02IbeDTRFZ9b4m0M4Kahlg)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_3;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_4;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_5;
	nimfr_("mustRehash", "strtabs.nim");
	result = (NIM_BOOL)0;
	nimln_(97, "strtabs.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_2));
	}
	LA3_: ;
	nimln_(98, "strtabs.nim");
	T5_ = (NIM_BOOL)0;
	TM_ZT9crccxweoChVXn9cHcxIXQ_3 = mulInt(length, ((NI) 2));
	TM_ZT9crccxweoChVXn9cHcxIXQ_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_3) < (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_4));
	if (T5_) goto LA6_;
	TM_ZT9crccxweoChVXn9cHcxIXQ_5 = subInt(length, counter);
	T5_ = ((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs)(NI h, NI maxHash) {
	NI result;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_6;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_7;
	nimfr_("nextTry", "strtabs.nim");
	result = (NI)0;
	nimln_(101, "strtabs.nim");
	TM_ZT9crccxweoChVXn9cHcxIXQ_6 = mulInt(((NI) 5), h);
	TM_ZT9crccxweoChVXn9cHcxIXQ_7 = addInt((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_6), ((NI) 1));
	result = (NI)((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_7) & maxHash);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, rawGet_g4UMXDeIi4hi42WuIY9cM4A_2)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NI result;
	NI h;
	NI T1_;
	NI T2_;
	nimfr_("rawGet", "strtabs.nim");
{	result = (NI)0;
	nimln_(104, "strtabs.nim");
	T1_ = (NI)0;
	T1_ = myhash_g4UMXDeIi4hi42WuIY9cM4A(t, key);
	T2_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		nimln_(105, "strtabs.nim");
		while (1) {
			NI T10_;
			if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
			if (!!(((*t).data->data[h].Field0 == 0))) goto LA4;
			nimln_(106, "strtabs.nim");
			{
				NIM_BOOL T7_;
				if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
				T7_ = (NIM_BOOL)0;
				T7_ = myCmp_6dqTqYQ9cC63hkWdN9br54EA(t, (*t).data->data[h].Field0, key);
				if (!T7_) goto LA8_;
				nimln_(107, "strtabs.nim");
				result = h;
				goto BeforeRet_;
			}
			LA8_: ;
			nimln_(108, "strtabs.nim");
			T10_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
			h = nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs(h, T10_);
		} LA4: ;
	}
	nimln_(109, "strtabs.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, nstTake)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index;
	nimfr_("[]", "strtabs.nim");
	result = (NimStringDesc**)0;
	nimln_(112, "strtabs.nim");
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	nimln_(125, "strtabs.nim");
	{
		nimln_(113, "strtabs.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index].Field1);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(116, "strtabs.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(125, "strtabs.nim");
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_8));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(116, "strtabs.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc**, mget_AtOx3IKEp1Smie6HNHB9buQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NimStringDesc** result;
	NI index;
	nimfr_("mget", "strtabs.nim");
	result = (NimStringDesc**)0;
	nimln_(112, "strtabs.nim");
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	nimln_(130, "strtabs.nim");
	{
		nimln_(113, "strtabs.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index].Field1);
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(116, "strtabs.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(130, "strtabs.nim");
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_8));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(116, "strtabs.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getOrDefault_sPC3Tb9bX9b1TxdHlL7x9cN3Q)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* default_0) {
	NimStringDesc* result;
	NI index;
	nimfr_("getOrDefault", "strtabs.nim");
	result = (NimStringDesc*)0;
	nimln_(133, "strtabs.nim");
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	nimln_(134, "strtabs.nim");
	{
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = copyString((*t).data->data[index].Field1);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(135, "strtabs.nim");
		result = copyString(default_0);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsthasKey)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("hasKey", "strtabs.nim");
	result = (NIM_BOOL)0;
	nimln_(139, "strtabs.nim");
	T1_ = (NI)0;
	T1_ = rawGet_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	result = (((NI) 0) <= T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_mzHkEOwMjp27RScMrhWA5A)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key) {
	NIM_BOOL result;
	nimfr_("contains", "strtabs.nim");
{	result = (NIM_BOOL)0;
	nimln_(143, "strtabs.nim");
	result = nsthasKey(t, key);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_YkqIveHDR3SuLUhxpyZbuQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySequence_4eQHGndY6XBYpFOH09apV8Q** data, NimStringDesc* key, NimStringDesc* val) {
	NI h;
	NI T1_;
	NI T2_;
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	nimfr_("rawInsert", "strtabs.nim");
	nimln_(146, "strtabs.nim");
	T1_ = (NI)0;
	T1_ = myhash_g4UMXDeIi4hi42WuIY9cM4A(t, key);
	T2_ = ((*data) ? ((*data)->Sup.len-1) : -1);
	h = (NI)(T1_ & T2_);
	{
		nimln_(147, "strtabs.nim");
		while (1) {
			NI T5_;
			if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
			if (!!(((*data)->data[h].Field0 == 0))) goto LA4;
			nimln_(148, "strtabs.nim");
			T5_ = ((*data) ? ((*data)->Sup.len-1) : -1);
			h = nextTry_4tI2vxIqcy1tNTBufKNbkgstrtabs(h, T5_);
		} LA4: ;
	}
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(149, "strtabs.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = (*data)->data[h].Field0; (*data)->data[h].Field0 = copyStringRC1(key);
	if (T6_) nimGCunrefNoCycle(T6_);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(150, "strtabs.nim");
	T7_ = (NimStringDesc*)0;
	T7_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(val);
	if (T7_) nimGCunrefNoCycle(T7_);
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q)(void* p, NI op) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* a;
	NI T1_;
	a = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field0, op);
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_1rn449bBULy9cLwCWr7ISAqg)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t) {
	tySequence_4eQHGndY6XBYpFOH09apV8Q* n;
	NI T1_;
	NI TM_ZT9crccxweoChVXn9cHcxIXQ_9;
	tySequence_4eQHGndY6XBYpFOH09apV8Q* T10_;
	nimfr_("enlarge", "strtabs.nim");
	n = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	nimln_(154, "strtabs.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_ZT9crccxweoChVXn9cHcxIXQ_9 = mulInt(T1_, ((NI) 2));
	n = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) newSeq((&NTI_4eQHGndY6XBYpFOH09apV8Q_), ((NI)chckRange((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_9), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI colontmp_;
		NI T3_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(155, "strtabs.nim");
		T3_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
		colontmp_ = T3_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_10;
				if (!(res <= colontmp_)) goto LA5;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(156, "strtabs.nim");
				{
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if (!!(((*t).data->data[i].Field0 == 0))) goto LA8_;
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					rawInsert_YkqIveHDR3SuLUhxpyZbuQ(t, (&n), (*t).data->data[i].Field0, (*t).data->data[i].Field1);
				}
				LA8_: ;
				nimln_(2035, "system.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_10 = addInt(res, ((NI) 1));
				res = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_10);
			} LA5: ;
		}
	}
	nimln_(157, "strtabs.nim");
	T10_ = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	T10_ = (*t).data;
	asgnRefNoCycle((void**) (&(*t).data), n);
	n = T10_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nstPut)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, NimStringDesc* key, NimStringDesc* val) {
	NI index;
	nimfr_("[]=", "strtabs.nim");
	nimln_(161, "strtabs.nim");
	index = rawGet_g4UMXDeIi4hi42WuIY9cM4A_2(t, key);
	nimln_(162, "strtabs.nim");
	{
		NimStringDesc* T5_;
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		nimln_(163, "strtabs.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*t).data->data[index].Field1; (*t).data->data[index].Field1 = copyStringRC1(val);
		if (T5_) nimGCunrefNoCycle(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_ZT9crccxweoChVXn9cHcxIXQ_11;
		nimln_(165, "strtabs.nim");
		{
			NI T9_;
			NIM_BOOL T10_;
			T9_ = ((*t).data ? (*t).data->Sup.len : 0);
			T10_ = (NIM_BOOL)0;
			T10_ = mustRehash_K02IbeDTRFZ9b4m0M4Kahlg(T9_, (*t).counter);
			if (!T10_) goto LA11_;
			enlarge_1rn449bBULy9cLwCWr7ISAqg(t);
		}
		LA11_: ;
		nimln_(166, "strtabs.nim");
		rawInsert_YkqIveHDR3SuLUhxpyZbuQ(t, (&(*t).data), key, val);
		nimln_(167, "strtabs.nim");
		TM_ZT9crccxweoChVXn9cHcxIXQ_11 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_11);
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, raiseFormatException_UlRj9cCVaVq3wqa9ckfyqy9cQ)(NimStringDesc* s) {
	tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
	NimStringDesc* T1_;
	nimfr_("raiseFormatException", "strtabs.nim");
	e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
	nimln_(171, "strtabs.nim");
	e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
	(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
	nimln_(172, "strtabs.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(s->Sup.len + 30);
appendString(T1_, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_12));
appendString(T1_, s);
	asgnRefNoCycle((void**) (&(*e).Sup.message), T1_);
	nimln_(173, "strtabs.nim");
	raiseException((Exception*)e, "ValueError");
	popFrame();
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getValue_mjQZRNgxAa33iqM216j4PQ)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySet_tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg flags, NimStringDesc* key) {
	NimStringDesc* result;
	nimfr_("getValue", "strtabs.nim");
{	result = (NimStringDesc*)0;
	nimln_(176, "strtabs.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nsthasKey(t, key);
		if (!T3_) goto LA4_;
		result = getOrDefault_sPC3Tb9bX9b1TxdHlL7x9cN3Q(t, key, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_13));
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(181, "strtabs.nim");
	{
		if (!((flags &(1U<<((NU)(((tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg) 0))&7U)))!=0)) goto LA8_;
		result = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(key, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_13));
	}
	goto LA6_;
	LA8_: ;
	{
		nimln_(182, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_13));
	}
	LA6_: ;
	nimln_(183, "strtabs.nim");
	{
		if (!((result ? result->Sup.len : 0) == ((NI) 0))) goto LA13_;
		nimln_(184, "strtabs.nim");
		{
			NimStringDesc* T19_;
			if (!((flags &(1U<<((NU)(((tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg) 2))&7U)))!=0)) goto LA17_;
			T19_ = (NimStringDesc*)0;
			T19_ = rawNewString(key->Sup.len + 1);
appendChar(T19_, 36);
appendString(T19_, key);
			result = T19_;
		}
		goto LA15_;
		LA17_: ;
		{
			nimln_(1212, "system.nim");
			nimln_(185, "strtabs.nim");
			if (!!(((flags &(1U<<((NU)(((tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg) 1))&7U)))!=0))) goto LA21_;
			raiseFormatException_UlRj9cCVaVq3wqa9ckfyqy9cQ(key);
		}
		goto LA15_;
		LA21_: ;
		LA15_: ;
	}
	LA13_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw)(void* p, NI op) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* a;
	a = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTable)(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	nimfr_("newStringTable", "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	nimln_(190, "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*) newObj((&NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_), sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw));
	(*result).Sup.m_type = (&NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_);
	nimln_(191, "strtabs.nim");
	(*result).mode = mode;
	nimln_(192, "strtabs.nim");
	(*result).counter = ((NI) 0);
	nimln_(193, "strtabs.nim");
	if ((*result).data) { nimGCunrefNoCycle((*result).data); (*result).data = NIM_NIL; }
	(*result).data = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) newSeqRC1((&NTI_4eQHGndY6XBYpFOH09apV8Q_), ((NI) 64));
	popFrame();
	return result;
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, clear_mr5fULczKYTosYcaVX0A0g)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* s, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	nimfr_("clear", "strtabs.nim");
	nimln_(197, "strtabs.nim");
	(*s).mode = mode;
	nimln_(198, "strtabs.nim");
	(*s).counter = ((NI) 0);
	nimln_(199, "strtabs.nim");
	(*s).data = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) setLengthSeq(&((*s).data)->Sup, sizeof(tyTuple_UV3llMMYFckfui8YMBuUZA), ((NI) 64));
	{
		NI i;
		NI colontmp_;
		NI T2_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(200, "strtabs.nim");
		T2_ = ((*s).data ? (*s).data->Sup.len : 0);
		colontmp_ = T2_;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_18;
				if (!(i_2 < colontmp_)) goto LA4;
				nimln_(3521, "system.nim");
				i = i_2;
				nimln_(201, "strtabs.nim");
				{
					NimStringDesc* T9_;
					if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
					if (!!(((*s).data->data[i].Field0 == 0))) goto LA7_;
					if ((NU)(i) >= (NU)((*s).data->Sup.len)) raiseIndexError();
					nimln_(202, "strtabs.nim");
					T9_ = (NimStringDesc*)0;
					T9_ = (*s).data->data[i].Field0; (*s).data->data[i].Field0 = copyStringRC1(NIM_NIL);
					if (T9_) nimGCunrefNoCycle(T9_);
				}
				LA7_: ;
				nimln_(3522, "system.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_18 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_18);
			} LA4: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithPairs)(NimStringDesc** keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	NI i;
	nimfr_("newStringTable", "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	nimln_(211, "strtabs.nim");
	result = nstnewStringTable(mode);
	nimln_(212, "strtabs.nim");
	i = ((NI) 0);
	{
		nimln_(213, "strtabs.nim");
		while (1) {
			NI TM_ZT9crccxweoChVXn9cHcxIXQ_19;
			NI TM_ZT9crccxweoChVXn9cHcxIXQ_20;
			if (!(i < (keyValuePairsLen_0-1))) goto LA2;
			nimln_(214, "strtabs.nim");
			if ((NU)(i) >= (NU)(keyValuePairsLen_0)) raiseIndexError();
			TM_ZT9crccxweoChVXn9cHcxIXQ_19 = addInt(i, ((NI) 1));
			if ((NU)((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_19)) >= (NU)(keyValuePairsLen_0)) raiseIndexError();
			nstPut(result, keyValuePairs[i], keyValuePairs[(NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_19)]);
			nimln_(215, "strtabs.nim");
			TM_ZT9crccxweoChVXn9cHcxIXQ_20 = addInt(i, ((NI) 2));
			i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_20);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*, nstnewStringTableWithTableConstr)(tyTuple_UV3llMMYFckfui8YMBuUZA* keyValuePairs, NI keyValuePairsLen_0, tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ mode) {
	tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* result;
	nimfr_("newStringTable", "strtabs.nim");
	result = (tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*)0;
	nimln_(224, "strtabs.nim");
	result = nstnewStringTable(mode);
	{
		NimStringDesc* key;
		NimStringDesc* val;
		NI i;
		key = (NimStringDesc*)0;
		val = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_21;
				if (!(i < keyValuePairsLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(keyValuePairsLen_0)) raiseIndexError();
				key = keyValuePairs[i].Field0;
				if ((NU)(i) >= (NU)(keyValuePairsLen_0)) raiseIndexError();
				val = keyValuePairs[i].Field1;
				nimln_(225, "strtabs.nim");
				nstPut(result, key, val);
				nimln_(2188, "system.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_21 = addInt(i, ((NI) 1));
				i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_21);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nstFormat)(NimStringDesc* f, tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t, tySet_tyEnum_FormatFlag_F4vlKAV4d0Kt9aXmu9cVNBrg flags) {
	NimStringDesc* result;
	NI i;
	nimfr_("%", "strtabs.nim");
	result = (NimStringDesc*)0;
	nimln_(232, "strtabs.nim");
	result = copyString(((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_13));
	nimln_(233, "strtabs.nim");
	i = ((NI) 0);
	{
		nimln_(234, "strtabs.nim");
		while (1) {
			if (!(i < (f ? f->Sup.len : 0))) goto LA2;
			nimln_(235, "strtabs.nim");
			{
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_22;
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				if (!((NU8)(f->data[i]) == (NU8)(36))) goto LA5_;
				nimln_(236, "strtabs.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_22 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_22)) > (NU)(f->Sup.len)) raiseIndexError();
				switch (((NU8)(f->data[(NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_22)]))) {
				case 36:
				{
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_23;
					nimln_(238, "strtabs.nim");
					result = addChar(result, 36);
					nimln_(239, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_23 = addInt(i, ((NI) 2));
					i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_23);
				}
				break;
				case 123:
				{
					NI j;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_24;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_26;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_27;
					NimStringDesc* T13_;
					NimStringDesc* T14_;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_28;
					nimln_(241, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_24 = addInt(i, ((NI) 1));
					j = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_24);
					{
						nimln_(242, "strtabs.nim");
						while (1) {
							NIM_BOOL T11_;
							NI TM_ZT9crccxweoChVXn9cHcxIXQ_25;
							T11_ = (NIM_BOOL)0;
							T11_ = (j < (f ? f->Sup.len : 0));
							if (!(T11_)) goto LA12_;
							nimln_(398, "system.nim");
							nimln_(242, "strtabs.nim");
							if ((NU)(j) > (NU)(f->Sup.len)) raiseIndexError();
							T11_ = !(((NU8)(f->data[j]) == (NU8)(125)));
							LA12_: ;
							if (!T11_) goto LA10;
							TM_ZT9crccxweoChVXn9cHcxIXQ_25 = addInt(j, ((NI) 1));
							j = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_25);
						} LA10: ;
					}
					nimln_(243, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_26 = addInt(i, ((NI) 2));
					TM_ZT9crccxweoChVXn9cHcxIXQ_27 = subInt(j, ((NI) 1));
					T13_ = (NimStringDesc*)0;
					T13_ = copyStrLast(f, (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_26), (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_27));
					T14_ = (NimStringDesc*)0;
					T14_ = getValue_mjQZRNgxAa33iqM216j4PQ(t, flags, T13_);
					result = resizeString(result, T14_->Sup.len + 0);
appendString(result, T14_);
					nimln_(244, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_28 = addInt(j, ((NI) 1));
					i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_28);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j_2;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_29;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_31;
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_32;
					NimStringDesc* T20_;
					NimStringDesc* T21_;
					nimln_(246, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_29 = addInt(i, ((NI) 1));
					j_2 = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_29);
					{
						nimln_(247, "strtabs.nim");
						while (1) {
							NIM_BOOL T18_;
							NI TM_ZT9crccxweoChVXn9cHcxIXQ_30;
							T18_ = (NIM_BOOL)0;
							T18_ = (j_2 < (f ? f->Sup.len : 0));
							if (!(T18_)) goto LA19_;
							if ((NU)(j_2) > (NU)(f->Sup.len)) raiseIndexError();
							T18_ = (((NU8)(f->data[j_2])) >= ((NU8)(97)) && ((NU8)(f->data[j_2])) <= ((NU8)(122)) || ((NU8)(f->data[j_2])) >= ((NU8)(65)) && ((NU8)(f->data[j_2])) <= ((NU8)(90)) || ((NU8)(f->data[j_2])) >= ((NU8)(48)) && ((NU8)(f->data[j_2])) <= ((NU8)(57)) || ((NU8)(f->data[j_2])) == ((NU8)(95)) || ((NU8)(f->data[j_2])) >= ((NU8)(128)) && ((NU8)(f->data[j_2])) <= ((NU8)(255)));
							LA19_: ;
							if (!T18_) goto LA17;
							TM_ZT9crccxweoChVXn9cHcxIXQ_30 = addInt(j_2, ((NI) 1));
							j_2 = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_30);
						} LA17: ;
					}
					nimln_(248, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_31 = addInt(i, ((NI) 1));
					TM_ZT9crccxweoChVXn9cHcxIXQ_32 = subInt(j_2, ((NI) 1));
					T20_ = (NimStringDesc*)0;
					T20_ = copyStrLast(f, (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_31), (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_32));
					T21_ = (NimStringDesc*)0;
					T21_ = getValue_mjQZRNgxAa33iqM216j4PQ(t, flags, T20_);
					result = resizeString(result, T21_->Sup.len + 0);
appendString(result, T21_);
					nimln_(249, "strtabs.nim");
					i = j_2;
				}
				break;
				default:
				{
					NI TM_ZT9crccxweoChVXn9cHcxIXQ_33;
					nimln_(251, "strtabs.nim");
					if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
					result = addChar(result, f->data[i]);
					nimln_(252, "strtabs.nim");
					TM_ZT9crccxweoChVXn9cHcxIXQ_33 = addInt(i, ((NI) 1));
					i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_33);
				}
				break;
				}
			}
			goto LA3_;
			LA5_: ;
			{
				NI TM_ZT9crccxweoChVXn9cHcxIXQ_34;
				nimln_(254, "strtabs.nim");
				if ((NU)(i) > (NU)(f->Sup.len)) raiseIndexError();
				result = addChar(result, f->data[i]);
				nimln_(255, "strtabs.nim");
				TM_ZT9crccxweoChVXn9cHcxIXQ_34 = addInt(i, ((NI) 1));
				i = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_34);
			}
			LA3_: ;
		} LA2: ;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nstDollar)(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw* t) {
	NimStringDesc* result;
	nimfr_("$", "strtabs.nim");
	result = (NimStringDesc*)0;
	nimln_(259, "strtabs.nim");
	{
		NI T3_;
		T3_ = (NI)0;
		T3_ = nstlen(t);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(260, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_35));
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(262, "strtabs.nim");
		result = copyString(((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_36));
		{
			NimStringDesc* key;
			NimStringDesc* val;
			key = (NimStringDesc*)0;
			val = (NimStringDesc*)0;
			{
				NI h;
				NI colontmp_;
				NI T9_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				nimln_(50, "strtabs.nim");
				T9_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
				colontmp_ = T9_;
				nimln_(2045, "system.nim");
				res = ((NI) 0);
				{
					nimln_(2046, "system.nim");
					while (1) {
						NI TM_ZT9crccxweoChVXn9cHcxIXQ_39;
						if (!(res <= colontmp_)) goto LA11;
						nimln_(2047, "system.nim");
						h = res;
						nimln_(51, "strtabs.nim");
						{
							if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							if (!!(((*t).data->data[h].Field0 == 0))) goto LA14_;
							nimln_(52, "strtabs.nim");
							if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							key = (*t).data->data[h].Field0;
							if ((NU)(h) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							val = (*t).data->data[h].Field1;
							nimln_(264, "strtabs.nim");
							{
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA18_;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_37));
							}
							LA18_: ;
							nimln_(265, "strtabs.nim");
							result = resizeString(result, key->Sup.len + 0);
appendString(result, key);
							nimln_(266, "strtabs.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_38));
							nimln_(267, "strtabs.nim");
							result = resizeString(result, val->Sup.len + 0);
appendString(result, val);
						}
						LA14_: ;
						nimln_(2048, "system.nim");
						TM_ZT9crccxweoChVXn9cHcxIXQ_39 = addInt(res, ((NI) 1));
						res = (NI)(TM_ZT9crccxweoChVXn9cHcxIXQ_39);
					} LA11: ;
				}
			}
		}
		nimln_(268, "strtabs.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_ZT9crccxweoChVXn9cHcxIXQ_40));
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void) {
	nimfr_("strtabs", "strtabs.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void) {
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_14[3];
static TNimNode* TM_ZT9crccxweoChVXn9cHcxIXQ_15[3];
NI TM_ZT9crccxweoChVXn9cHcxIXQ_17;
static char* NIM_CONST TM_ZT9crccxweoChVXn9cHcxIXQ_16[3] = {
"modeCaseSensitive", 
"modeCaseInsensitive", 
"modeStyleInsensitive"};
static TNimNode TM_ZT9crccxweoChVXn9cHcxIXQ_0[8];
NTI_4eQHGndY6XBYpFOH09apV8Q_.size = sizeof(tySequence_4eQHGndY6XBYpFOH09apV8Q*);
NTI_4eQHGndY6XBYpFOH09apV8Q_.kind = 24;
NTI_4eQHGndY6XBYpFOH09apV8Q_.base = (&NTI_UV3llMMYFckfui8YMBuUZA_);
NTI_4eQHGndY6XBYpFOH09apV8Q_.flags = 2;
NTI_4eQHGndY6XBYpFOH09apV8Q_.marker = Marker_tySequence_4eQHGndY6XBYpFOH09apV8Q;
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.size = sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw);
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.kind = 17;
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_ZT9crccxweoChVXn9cHcxIXQ_14[0] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[1];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, counter);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[1].name = "counter";
TM_ZT9crccxweoChVXn9cHcxIXQ_14[1] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[2];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, data);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].typ = (&NTI_4eQHGndY6XBYpFOH09apV8Q_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[2].name = "data";
TM_ZT9crccxweoChVXn9cHcxIXQ_14[2] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[3];
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.size = sizeof(tyEnum_StringTableMode_G9c4wVDFIzf0xHmQvxso9a9cQ);
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.kind = 14;
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.base = 0;
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.flags = 3;
for (TM_ZT9crccxweoChVXn9cHcxIXQ_17 = 0; TM_ZT9crccxweoChVXn9cHcxIXQ_17 < 3; TM_ZT9crccxweoChVXn9cHcxIXQ_17++) {
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_17+4].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_17+4].offset = TM_ZT9crccxweoChVXn9cHcxIXQ_17;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_17+4].name = TM_ZT9crccxweoChVXn9cHcxIXQ_16[TM_ZT9crccxweoChVXn9cHcxIXQ_17];
TM_ZT9crccxweoChVXn9cHcxIXQ_15[TM_ZT9crccxweoChVXn9cHcxIXQ_17] = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[TM_ZT9crccxweoChVXn9cHcxIXQ_17+4];
}
TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[7].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_15[0];
NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[7];
TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].kind = 1;
TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].offset = offsetof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw, mode);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].typ = (&NTI_G9c4wVDFIzf0xHmQvxso9a9cQ_);
TM_ZT9crccxweoChVXn9cHcxIXQ_0[3].name = "mode";
TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].len = 3; TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].kind = 2; TM_ZT9crccxweoChVXn9cHcxIXQ_0[0].sons = &TM_ZT9crccxweoChVXn9cHcxIXQ_14[0];
NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_.node = &TM_ZT9crccxweoChVXn9cHcxIXQ_0[0];
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.size = sizeof(tyObject_StringTableObj_DKRIdH9c9cKI7YpQb9c0wKlEw*);
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.kind = 22;
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.base = (&NTI_DKRIdH9c9cKI7YpQb9c0wKlEw_);
NTI_pkhT5bYRU9ayIZ9cBuuCx4Xw_.marker = Marker_tyRef_pkhT5bYRU9ayIZ9cBuuCx4Xw;
}

