/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/user/Dropbox/projects/nim/stui/devtools/nimcache/stdlib_colors.o /home/user/Dropbox/projects/nim/stui/devtools/nimcache/stdlib_colors.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_47w2DboNEPf69aPgubZdd7Q tyTuple_47w2DboNEPf69aPgubZdd7Q;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyTuple_47w2DboNEPf69aPgubZdd7Q {
NI Field0;
NI Field1;
NI Field2;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
typedef tyTuple_XOVT24GHXwqiEj5GCsEGCA tyArray_q6NkqhYAaVnMZpcgQ6A6Fg[140];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, satPlus_eBbWMf0ghXjNCk0Jl2gnOQcolors)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, satMinus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, plus__gJIJ0TjY9cb0kRs9aHpNdEoA)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, minus__gJIJ0TjY9cb0kRs9aHpNdEoA_2)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyTuple_47w2DboNEPf69aPgubZdd7Q, extractRGB_BBeGhczeu0Oe9b4tbckVIHA)(NI a);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(NI, intensity_V4kCo8fXOcLWbXWVP5cyEw)(NI a, NF f);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__4qHnIinwHK8uhOG9bivSS9cA)(NI c);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NI, binaryStrSearch_sfDfYBE9cjkr66pIi04EogQ)(tyTuple_XOVT24GHXwqiEj5GCsEGCA* x, NI xLen_0, NimStringDesc* y);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_LIB_PRIVATE N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x, NimStringDesc* y);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NI, parseColor_GKC40jw0DFGObWjkYljZnw)(NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isColor_pxBV1VWuv6nVnMvTQgopyg)(NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(NI, rgb_s6fKO9c2ZHh9bXQ1gD9as9bwtw)(NI r, NI g, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_47w2DboNEPf69aPgubZdd7Q_;
extern TNimType NTI_Oicxd75j1oQ6Xr53IdlvoA_;
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_2, "aliceblue", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_3, "antiquewhite", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_4, "aqua", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_5, "aquamarine", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_6, "azure", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_7, "beige", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_8, "bisque", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_9, "black", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_10, "blanchedalmond", 14);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_11, "blue", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_12, "blueviolet", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_13, "brown", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_14, "burlywood", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_15, "cadetblue", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_16, "chartreuse", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_17, "chocolate", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_18, "coral", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_19, "cornflowerblue", 14);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_20, "cornsilk", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_21, "crimson", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_22, "cyan", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_23, "darkblue", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_24, "darkcyan", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_25, "darkgoldenrod", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_26, "darkgray", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_27, "darkgreen", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_28, "darkkhaki", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_29, "darkmagenta", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_30, "darkolivegreen", 14);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_31, "darkorange", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_32, "darkorchid", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_33, "darkred", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_34, "darksalmon", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_35, "darkseagreen", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_36, "darkslateblue", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_37, "darkslategray", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_38, "darkturquoise", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_39, "darkviolet", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_40, "deeppink", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_41, "deepskyblue", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_42, "dimgray", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_43, "dodgerblue", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_44, "firebrick", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_45, "floralwhite", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_46, "forestgreen", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_47, "fuchsia", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_48, "gainsboro", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_49, "ghostwhite", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_50, "gold", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_51, "goldenrod", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_52, "gray", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_53, "green", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_54, "greenyellow", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_55, "honeydew", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_56, "hotpink", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_57, "indianred", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_58, "indigo", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_59, "ivory", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_60, "khaki", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_61, "lavender", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_62, "lavenderblush", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_63, "lawngreen", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_64, "lemonchiffon", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_65, "lightblue", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_66, "lightcoral", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_67, "lightcyan", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_68, "lightgoldenrodyellow", 20);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_69, "lightgrey", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_70, "lightgreen", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_71, "lightpink", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_72, "lightsalmon", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_73, "lightseagreen", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_74, "lightskyblue", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_75, "lightslategray", 14);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_76, "lightsteelblue", 14);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_77, "lightyellow", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_78, "lime", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_79, "limegreen", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_80, "linen", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_81, "magenta", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_82, "maroon", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_83, "mediumaquamarine", 16);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_84, "mediumblue", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_85, "mediumorchid", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_86, "mediumpurple", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_87, "mediumseagreen", 14);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_88, "mediumslateblue", 15);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_89, "mediumspringgreen", 17);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_90, "mediumturquoise", 15);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_91, "mediumvioletred", 15);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_92, "midnightblue", 12);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_93, "mintcream", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_94, "mistyrose", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_95, "moccasin", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_96, "navajowhite", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_97, "navy", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_98, "oldlace", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_99, "olive", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_100, "olivedrab", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_101, "orange", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_102, "orangered", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_103, "orchid", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_104, "palegoldenrod", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_105, "palegreen", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_106, "paleturquoise", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_107, "palevioletred", 13);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_108, "papayawhip", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_109, "peachpuff", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_110, "peru", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_111, "pink", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_112, "plum", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_113, "powderblue", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_114, "purple", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_115, "red", 3);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_116, "rosybrown", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_117, "royalblue", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_118, "saddlebrown", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_119, "salmon", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_120, "sandybrown", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_121, "seagreen", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_122, "seashell", 8);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_123, "sienna", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_124, "silver", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_125, "skyblue", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_126, "slateblue", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_127, "slategray", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_128, "snow", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_129, "springgreen", 11);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_130, "steelblue", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_131, "tan", 3);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_132, "teal", 4);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_133, "thistle", 7);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_134, "tomato", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_135, "turquoise", 9);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_136, "violet", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_137, "wheat", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_138, "white", 5);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_139, "whitesmoke", 10);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_140, "yellow", 6);
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_141, "yellowgreen", 11);
NIM_CONST tyArray_q6NkqhYAaVnMZpcgQ6A6Fg colorNames_U7tp4PMw3jdOdV56ZMGhvA = {{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_2),
((NI) 15792383)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_3),
((NI) 16444375)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_4),
((NI) 65535)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_5),
((NI) 8388564)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_6),
((NI) 15794175)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_7),
((NI) 16119260)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_8),
((NI) 16770244)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_9),
((NI) 0)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_10),
((NI) 16772045)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_11),
((NI) 255)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_12),
((NI) 9055202)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_13),
((NI) 10824234)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_14),
((NI) 14596231)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_15),
((NI) 6266528)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_16),
((NI) 8388352)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_17),
((NI) 13789470)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_18),
((NI) 16744272)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_19),
((NI) 6591981)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_20),
((NI) 16775388)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_21),
((NI) 14423100)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_22),
((NI) 65535)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_23),
((NI) 139)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_24),
((NI) 35723)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_25),
((NI) 12092939)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_26),
((NI) 11119017)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_27),
((NI) 25600)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_28),
((NI) 12433259)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_29),
((NI) 9109643)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_30),
((NI) 5597999)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_31),
((NI) 16747520)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_32),
((NI) 10040012)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_33),
((NI) 9109504)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_34),
((NI) 15308410)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_35),
((NI) 9419919)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_36),
((NI) 4734347)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_37),
((NI) 3100495)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_38),
((NI) 52945)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_39),
((NI) 9699539)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_40),
((NI) 16716947)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_41),
((NI) 49151)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_42),
((NI) 6908265)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_43),
((NI) 2003199)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_44),
((NI) 11674146)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_45),
((NI) 16775920)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_46),
((NI) 2263842)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_47),
((NI) 16711935)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_48),
((NI) 14474460)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_49),
((NI) 16316671)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_50),
((NI) 16766720)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_51),
((NI) 14329120)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_52),
((NI) 8421504)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_53),
((NI) 32768)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_54),
((NI) 11403055)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_55),
((NI) 15794160)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_56),
((NI) 16738740)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_57),
((NI) 13458524)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_58),
((NI) 4915330)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_59),
((NI) 16777200)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_60),
((NI) 15787660)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_61),
((NI) 15132410)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_62),
((NI) 16773365)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_63),
((NI) 8190976)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_64),
((NI) 16775885)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_65),
((NI) 11393254)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_66),
((NI) 15761536)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_67),
((NI) 14745599)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_68),
((NI) 16448210)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_69),
((NI) 13882323)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_70),
((NI) 9498256)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_71),
((NI) 16758465)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_72),
((NI) 16752762)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_73),
((NI) 2142890)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_74),
((NI) 8900346)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_75),
((NI) 7833753)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_76),
((NI) 11584734)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_77),
((NI) 16777184)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_78),
((NI) 65280)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_79),
((NI) 3329330)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_80),
((NI) 16445670)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_81),
((NI) 16711935)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_82),
((NI) 8388608)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_83),
((NI) 6737322)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_84),
((NI) 205)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_85),
((NI) 12211667)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_86),
((NI) 9662680)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_87),
((NI) 3978097)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_88),
((NI) 8087790)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_89),
((NI) 64154)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_90),
((NI) 4772300)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_91),
((NI) 13047173)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_92),
((NI) 1644912)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_93),
((NI) 16121850)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_94),
((NI) 16770273)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_95),
((NI) 16770229)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_96),
((NI) 16768685)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_97),
((NI) 128)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_98),
((NI) 16643558)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_99),
((NI) 8421376)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_100),
((NI) 7048739)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_101),
((NI) 16753920)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_102),
((NI) 16729344)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_103),
((NI) 14315734)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_104),
((NI) 15657130)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_105),
((NI) 10025880)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_106),
((NI) 11529966)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_107),
((NI) 14184595)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_108),
((NI) 16773077)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_109),
((NI) 16767673)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_110),
((NI) 13468991)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_111),
((NI) 16761035)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_112),
((NI) 14524637)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_113),
((NI) 11591910)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_114),
((NI) 8388736)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_115),
((NI) 16711680)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_116),
((NI) 12357519)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_117),
((NI) 4286945)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_118),
((NI) 9127187)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_119),
((NI) 16416882)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_120),
((NI) 16032864)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_121),
((NI) 3050327)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_122),
((NI) 16774638)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_123),
((NI) 10506797)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_124),
((NI) 12632256)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_125),
((NI) 8900331)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_126),
((NI) 6970061)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_127),
((NI) 7372944)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_128),
((NI) 16775930)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_129),
((NI) 65407)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_130),
((NI) 4620980)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_131),
((NI) 13808780)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_132),
((NI) 32896)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_133),
((NI) 14204888)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_134),
((NI) 16737095)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_135),
((NI) 4251856)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_136),
((NI) 15631086)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_137),
((NI) 16113331)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_138),
((NI) 16777215)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_139),
((NI) 16119285)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_140),
((NI) 16776960)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_141),
((NI) 10145074)}
}
;
NIM_CONST tyArray_q6NkqhYAaVnMZpcgQ6A6Fg TM_IeCO5P1bEFfytAeZMzA9bFg_147 = {{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_2),
((NI) 15792383)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_3),
((NI) 16444375)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_4),
((NI) 65535)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_5),
((NI) 8388564)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_6),
((NI) 15794175)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_7),
((NI) 16119260)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_8),
((NI) 16770244)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_9),
((NI) 0)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_10),
((NI) 16772045)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_11),
((NI) 255)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_12),
((NI) 9055202)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_13),
((NI) 10824234)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_14),
((NI) 14596231)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_15),
((NI) 6266528)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_16),
((NI) 8388352)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_17),
((NI) 13789470)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_18),
((NI) 16744272)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_19),
((NI) 6591981)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_20),
((NI) 16775388)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_21),
((NI) 14423100)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_22),
((NI) 65535)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_23),
((NI) 139)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_24),
((NI) 35723)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_25),
((NI) 12092939)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_26),
((NI) 11119017)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_27),
((NI) 25600)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_28),
((NI) 12433259)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_29),
((NI) 9109643)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_30),
((NI) 5597999)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_31),
((NI) 16747520)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_32),
((NI) 10040012)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_33),
((NI) 9109504)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_34),
((NI) 15308410)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_35),
((NI) 9419919)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_36),
((NI) 4734347)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_37),
((NI) 3100495)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_38),
((NI) 52945)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_39),
((NI) 9699539)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_40),
((NI) 16716947)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_41),
((NI) 49151)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_42),
((NI) 6908265)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_43),
((NI) 2003199)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_44),
((NI) 11674146)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_45),
((NI) 16775920)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_46),
((NI) 2263842)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_47),
((NI) 16711935)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_48),
((NI) 14474460)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_49),
((NI) 16316671)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_50),
((NI) 16766720)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_51),
((NI) 14329120)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_52),
((NI) 8421504)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_53),
((NI) 32768)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_54),
((NI) 11403055)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_55),
((NI) 15794160)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_56),
((NI) 16738740)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_57),
((NI) 13458524)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_58),
((NI) 4915330)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_59),
((NI) 16777200)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_60),
((NI) 15787660)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_61),
((NI) 15132410)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_62),
((NI) 16773365)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_63),
((NI) 8190976)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_64),
((NI) 16775885)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_65),
((NI) 11393254)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_66),
((NI) 15761536)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_67),
((NI) 14745599)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_68),
((NI) 16448210)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_69),
((NI) 13882323)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_70),
((NI) 9498256)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_71),
((NI) 16758465)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_72),
((NI) 16752762)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_73),
((NI) 2142890)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_74),
((NI) 8900346)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_75),
((NI) 7833753)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_76),
((NI) 11584734)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_77),
((NI) 16777184)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_78),
((NI) 65280)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_79),
((NI) 3329330)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_80),
((NI) 16445670)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_81),
((NI) 16711935)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_82),
((NI) 8388608)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_83),
((NI) 6737322)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_84),
((NI) 205)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_85),
((NI) 12211667)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_86),
((NI) 9662680)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_87),
((NI) 3978097)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_88),
((NI) 8087790)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_89),
((NI) 64154)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_90),
((NI) 4772300)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_91),
((NI) 13047173)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_92),
((NI) 1644912)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_93),
((NI) 16121850)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_94),
((NI) 16770273)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_95),
((NI) 16770229)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_96),
((NI) 16768685)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_97),
((NI) 128)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_98),
((NI) 16643558)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_99),
((NI) 8421376)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_100),
((NI) 7048739)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_101),
((NI) 16753920)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_102),
((NI) 16729344)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_103),
((NI) 14315734)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_104),
((NI) 15657130)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_105),
((NI) 10025880)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_106),
((NI) 11529966)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_107),
((NI) 14184595)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_108),
((NI) 16773077)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_109),
((NI) 16767673)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_110),
((NI) 13468991)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_111),
((NI) 16761035)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_112),
((NI) 14524637)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_113),
((NI) 11591910)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_114),
((NI) 8388736)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_115),
((NI) 16711680)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_116),
((NI) 12357519)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_117),
((NI) 4286945)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_118),
((NI) 9127187)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_119),
((NI) 16416882)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_120),
((NI) 16032864)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_121),
((NI) 3050327)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_122),
((NI) 16774638)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_123),
((NI) 10506797)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_124),
((NI) 12632256)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_125),
((NI) 8900331)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_126),
((NI) 6970061)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_127),
((NI) 7372944)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_128),
((NI) 16775930)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_129),
((NI) 65407)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_130),
((NI) 4620980)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_131),
((NI) 13808780)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_132),
((NI) 32896)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_133),
((NI) 14204888)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_134),
((NI) 16737095)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_135),
((NI) 4251856)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_136),
((NI) 15631086)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_137),
((NI) 16113331)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_138),
((NI) 16777215)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_139),
((NI) 16119285)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_140),
((NI) 16776960)}
,
{((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_141),
((NI) 10145074)}
}
;
STRING_LITERAL(TM_IeCO5P1bEFfytAeZMzA9bFg_148, "unknown color: ", 15);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, satPlus_eBbWMf0ghXjNCk0Jl2gnOQcolors)(NI a, NI b) {
	NI result;
	nimfr_("satPlus", "colors.nim");
	result = (NI)0;
	nimln_(36, "colors.nim");
	result = (NI)((NU64)(a) + (NU64)(b));
	nimln_(37, "colors.nim");
	{
		if (!(((NI) 255) < result)) goto LA3_;
		result = ((NI) 255);
	}
	LA3_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, satMinus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors)(NI a, NI b) {
	NI result;
	nimfr_("satMinus", "colors.nim");
	result = (NI)0;
	nimln_(40, "colors.nim");
	result = (NI)((NU64)(a) - (NU64)(b));
	nimln_(41, "colors.nim");
	{
		if (!(result < ((NI) 0))) goto LA3_;
		result = ((NI) 0);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, plus__gJIJ0TjY9cb0kRs9aHpNdEoA)(NI a, NI b) {
	NI result;
	NI ar;
	NI ag;
	NI ab;
	NI br;
	NI bg;
	NI bb;
	NI T1_;
	NI T2_;
	NI T3_;
	nimfr_("+", "colors.nim");
	result = (NI)0;
	nimln_(44, "colors.nim");
	nimln_(23, "colors.nim");
	ar = (NI)((NI)((NU64)(a) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln_(24, "colors.nim");
	ag = (NI)((NI)((NU64)(a) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln_(25, "colors.nim");
	ab = (NI)(a & ((NI) 255));
	nimln_(23, "colors.nim");
	br = (NI)((NI)((NU64)(b) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln_(24, "colors.nim");
	bg = (NI)((NI)((NU64)(b) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln_(25, "colors.nim");
	bb = (NI)(b & ((NI) 255));
	nimln_(28, "colors.nim");
	nimln_(33, "colors.nim");
	T1_ = (NI)0;
	T1_ = satPlus_eBbWMf0ghXjNCk0Jl2gnOQcolors(ar, br);
	T2_ = (NI)0;
	T2_ = satPlus_eBbWMf0ghXjNCk0Jl2gnOQcolors(ag, bg);
	T3_ = (NI)0;
	T3_ = satPlus_eBbWMf0ghXjNCk0Jl2gnOQcolors(ab, bb);
	result = (NI)((NI)((NI)((NU64)(T1_) << (NU64)(((NI) 16))) | (NI)((NU64)(T2_) << (NU64)(((NI) 8)))) | T3_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, minus__gJIJ0TjY9cb0kRs9aHpNdEoA_2)(NI a, NI b) {
	NI result;
	NI ar;
	NI ag;
	NI ab;
	NI br;
	NI bg;
	NI bb;
	NI T1_;
	NI T2_;
	NI T3_;
	nimfr_("-", "colors.nim");
	result = (NI)0;
	nimln_(49, "colors.nim");
	nimln_(23, "colors.nim");
	ar = (NI)((NI)((NU64)(a) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln_(24, "colors.nim");
	ag = (NI)((NI)((NU64)(a) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln_(25, "colors.nim");
	ab = (NI)(a & ((NI) 255));
	nimln_(23, "colors.nim");
	br = (NI)((NI)((NU64)(b) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln_(24, "colors.nim");
	bg = (NI)((NI)((NU64)(b) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln_(25, "colors.nim");
	bb = (NI)(b & ((NI) 255));
	nimln_(28, "colors.nim");
	nimln_(33, "colors.nim");
	T1_ = (NI)0;
	T1_ = satMinus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors(ar, br);
	T2_ = (NI)0;
	T2_ = satMinus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors(ag, bg);
	T3_ = (NI)0;
	T3_ = satMinus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors(ab, bb);
	result = (NI)((NI)((NI)((NU64)(T1_) << (NU64)(((NI) 16))) | (NI)((NU64)(T2_) << (NU64)(((NI) 8)))) | T3_);
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_47w2DboNEPf69aPgubZdd7Q, extractRGB_BBeGhczeu0Oe9b4tbckVIHA)(NI a) {
	tyTuple_47w2DboNEPf69aPgubZdd7Q result;
	nimfr_("extractRGB", "colors.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(55, "colors.nim");
	result.Field0 = ((NI)chckRange((NI)((NI)((NU64)(a) >> (NU64)(((NI) 16))) & ((NI) 255)), ((NI) 0), ((NI) 255)));
	nimln_(56, "colors.nim");
	result.Field1 = ((NI)chckRange((NI)((NI)((NU64)(a) >> (NU64)(((NI) 8))) & ((NI) 255)), ((NI) 0), ((NI) 255)));
	nimln_(57, "colors.nim");
	result.Field2 = ((NI)chckRange((NI)(a & ((NI) 255)), ((NI) 0), ((NI) 255)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, intensity_V4kCo8fXOcLWbXWVP5cyEw)(NI a, NF f) {
	NI result;
	NI r;
	NI g;
	NI b;
	nimfr_("intensity", "colors.nim");
	result = (NI)0;
	nimln_(62, "colors.nim");
	r = float64ToInt32(((NF)(((double) ((NI)((NI)((NU64)(a) >> (NU64)(((NI) 16))) & ((NI) 255))))) * (NF)(f)));
	nimln_(63, "colors.nim");
	g = float64ToInt32(((NF)(((double) ((NI)((NI)((NU64)(a) >> (NU64)(((NI) 8))) & ((NI) 255))))) * (NF)(f)));
	nimln_(64, "colors.nim");
	b = float64ToInt32(((NF)(((double) ((NI)(a & ((NI) 255))))) * (NF)(f)));
	nimln_(65, "colors.nim");
	{
		if (!((NU64)(((NI) 255)) < (NU64)(r))) goto LA3_;
		r = ((NI) 255);
	}
	LA3_: ;
	nimln_(66, "colors.nim");
	{
		if (!((NU64)(((NI) 255)) < (NU64)(g))) goto LA7_;
		g = ((NI) 255);
	}
	LA7_: ;
	nimln_(67, "colors.nim");
	{
		if (!((NU64)(((NI) 255)) < (NU64)(b))) goto LA11_;
		b = ((NI) 255);
	}
	LA11_: ;
	nimln_(68, "colors.nim");
	nimln_(28, "colors.nim");
	nimln_(68, "colors.nim");
	result = (NI)((NI)((NI)((NU64)(r) << (NU64)(((NI) 16))) | (NI)((NU64)(g) << (NU64)(((NI) 8)))) | b);
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__4qHnIinwHK8uhOG9bivSS9cA)(NI c) {
	NimStringDesc* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("$", "colors.nim");
	result = (NimStringDesc*)0;
	nimln_(374, "colors.nim");
	T1_ = (NimStringDesc*)0;
	T2_ = (NimStringDesc*)0;
	T2_ = nsuToHex(((NI64) (c)), ((NI) 6));
	T1_ = rawNewString(T2_->Sup.len + 1);
appendChar(T1_, 35);
appendString(T1_, T2_);
	result = T1_;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, binaryStrSearch_sfDfYBE9cjkr66pIi04EogQ)(tyTuple_XOVT24GHXwqiEj5GCsEGCA* x, NI xLen_0, NimStringDesc* y) {
	NI result;
	NI a;
	NI b;
	NI TM_IeCO5P1bEFfytAeZMzA9bFg_142;
	nimfr_("binaryStrSearch", "colors.nim");
{	result = (NI)0;
	nimln_(378, "colors.nim");
	a = ((NI) 0);
	nimln_(379, "colors.nim");
	TM_IeCO5P1bEFfytAeZMzA9bFg_142 = subInt(xLen_0, ((NI) 1));
	b = (NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_142);
	{
		nimln_(380, "colors.nim");
		while (1) {
			NI mid;
			NI TM_IeCO5P1bEFfytAeZMzA9bFg_143;
			NI TM_IeCO5P1bEFfytAeZMzA9bFg_144;
			NI c;
			if (!(a <= b)) goto LA2;
			nimln_(381, "colors.nim");
			TM_IeCO5P1bEFfytAeZMzA9bFg_143 = addInt(a, b);
			TM_IeCO5P1bEFfytAeZMzA9bFg_144 = divInt((NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_143), ((NI) 2));
			mid = (NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_144);
			nimln_(382, "colors.nim");
			if ((NU)(mid) >= (NU)(xLen_0)) raiseIndexError();
			c = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(x[mid].Field0, y);
			nimln_(383, "colors.nim");
			{
				NI TM_IeCO5P1bEFfytAeZMzA9bFg_145;
				if (!(c < ((NI) 0))) goto LA5_;
				TM_IeCO5P1bEFfytAeZMzA9bFg_145 = addInt(mid, ((NI) 1));
				a = (NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_145);
			}
			goto LA3_;
			LA5_: ;
			{
				NI TM_IeCO5P1bEFfytAeZMzA9bFg_146;
				nimln_(384, "colors.nim");
				if (!(((NI) 0) < c)) goto LA8_;
				TM_IeCO5P1bEFfytAeZMzA9bFg_146 = subInt(mid, ((NI) 1));
				b = (NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_146);
			}
			goto LA3_;
			LA8_: ;
			{
				nimln_(385, "colors.nim");
				result = mid;
				goto BeforeRet_;
			}
			LA3_: ;
		} LA2: ;
	}
	nimln_(386, "colors.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, parseColor_GKC40jw0DFGObWjkYljZnw)(NimStringDesc* name) {
	NI result;
	nimfr_("parseColor", "colors.nim");
	result = (NI)0;
	nimln_(391, "colors.nim");
	{
		if ((NU)(((NI) 0)) > (NU)(name->Sup.len)) raiseIndexError();
		if (!((NU8)(name->data[((NI) 0)]) == (NU8)(35))) goto LA3_;
		nimln_(392, "colors.nim");
		result = nsuParseHexInt(name);
	}
	goto LA1_;
	LA3_: ;
	{
		NI idx;
		nimln_(394, "colors.nim");
		idx = binaryStrSearch_sfDfYBE9cjkr66pIi04EogQ(TM_IeCO5P1bEFfytAeZMzA9bFg_147, 140, name);
		nimln_(395, "colors.nim");
		{
			tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
			NimStringDesc* T10_;
			if (!(idx < ((NI) 0))) goto LA8_;
			e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
			nimln_(2811, "system.nim");
			e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
			(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
			nimln_(395, "colors.nim");
			T10_ = (NimStringDesc*)0;
			T10_ = rawNewString(name->Sup.len + 15);
appendString(T10_, ((NimStringDesc*) &TM_IeCO5P1bEFfytAeZMzA9bFg_148));
appendString(T10_, name);
			asgnRefNoCycle((void**) (&(*e).Sup.message), T10_);
			nimln_(2806, "system.nim");
			asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
			nimln_(395, "colors.nim");
			raiseException((Exception*)e, "ValueError");
		}
		LA8_: ;
		nimln_(396, "colors.nim");
		if ((NU)(idx) > (NU)(139)) raiseIndexError();
		result = colorNames_U7tp4PMw3jdOdV56ZMGhvA[(idx)- 0].Field1;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isColor_pxBV1VWuv6nVnMvTQgopyg)(NimStringDesc* name) {
	NIM_BOOL result;
	nimfr_("isColor", "colors.nim");
{	result = (NIM_BOOL)0;
	nimln_(401, "colors.nim");
	{
		if ((NU)(((NI) 0)) > (NU)(name->Sup.len)) raiseIndexError();
		if (!((NU8)(name->data[((NI) 0)]) == (NU8)(35))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI TM_IeCO5P1bEFfytAeZMzA9bFg_149;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(402, "colors.nim");
			TM_IeCO5P1bEFfytAeZMzA9bFg_149 = subInt((name ? name->Sup.len : 0), ((NI) 1));
			colontmp_ = (NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_149);
			nimln_(2045, "system.nim");
			res = ((NI) 1);
			{
				nimln_(2046, "system.nim");
				while (1) {
					NI TM_IeCO5P1bEFfytAeZMzA9bFg_150;
					if (!(res <= colontmp_)) goto LA7;
					nimln_(2047, "system.nim");
					i = res;
					nimln_(403, "colors.nim");
					{
						nimln_(1212, "system.nim");
						nimln_(403, "colors.nim");
						if ((NU)(i) > (NU)(name->Sup.len)) raiseIndexError();
						if (!!((((NU8)(name->data[i])) >= ((NU8)(48)) && ((NU8)(name->data[i])) <= ((NU8)(57)) || ((NU8)(name->data[i])) >= ((NU8)(97)) && ((NU8)(name->data[i])) <= ((NU8)(102)) || ((NU8)(name->data[i])) >= ((NU8)(65)) && ((NU8)(name->data[i])) <= ((NU8)(70))))) goto LA10_;
						result = NIM_FALSE;
						goto BeforeRet_;
					}
					LA10_: ;
					nimln_(2048, "system.nim");
					TM_IeCO5P1bEFfytAeZMzA9bFg_150 = addInt(res, ((NI) 1));
					res = (NI)(TM_IeCO5P1bEFfytAeZMzA9bFg_150);
				} LA7: ;
			}
		}
		nimln_(404, "colors.nim");
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NI T13_;
		nimln_(406, "colors.nim");
		nimln_(230, "colors.nim");
		T13_ = (NI)0;
		T13_ = binaryStrSearch_sfDfYBE9cjkr66pIi04EogQ(TM_IeCO5P1bEFfytAeZMzA9bFg_147, 140, name);
		result = (((NI) 0) <= T13_);
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, rgb_s6fKO9c2ZHh9bXQ1gD9as9bwtw)(NI r, NI g, NI b) {
	NI result;
	nimfr_("rgb", "colors.nim");
	result = (NI)0;
	nimln_(410, "colors.nim");
	nimln_(28, "colors.nim");
	nimln_(410, "colors.nim");
	result = (NI)((NI)((NI)((NU64)(((NI) (r))) << (NU64)(((NI) 16))) | (NI)((NU64)(((NI) (g))) << (NU64)(((NI) 8)))) | ((NI) (b)));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit000)(void) {
	nimfr_("colors", "colors.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit000)(void) {
static TNimNode* TM_IeCO5P1bEFfytAeZMzA9bFg_151[3];
static TNimNode TM_IeCO5P1bEFfytAeZMzA9bFg_0[4];
NTI_47w2DboNEPf69aPgubZdd7Q_.size = sizeof(tyTuple_47w2DboNEPf69aPgubZdd7Q);
NTI_47w2DboNEPf69aPgubZdd7Q_.kind = 18;
NTI_47w2DboNEPf69aPgubZdd7Q_.base = 0;
NTI_47w2DboNEPf69aPgubZdd7Q_.flags = 3;
TM_IeCO5P1bEFfytAeZMzA9bFg_151[0] = &TM_IeCO5P1bEFfytAeZMzA9bFg_0[1];
TM_IeCO5P1bEFfytAeZMzA9bFg_0[1].kind = 1;
TM_IeCO5P1bEFfytAeZMzA9bFg_0[1].offset = offsetof(tyTuple_47w2DboNEPf69aPgubZdd7Q, Field0);
TM_IeCO5P1bEFfytAeZMzA9bFg_0[1].typ = (&NTI_Oicxd75j1oQ6Xr53IdlvoA_);
TM_IeCO5P1bEFfytAeZMzA9bFg_0[1].name = "Field0";
TM_IeCO5P1bEFfytAeZMzA9bFg_151[1] = &TM_IeCO5P1bEFfytAeZMzA9bFg_0[2];
TM_IeCO5P1bEFfytAeZMzA9bFg_0[2].kind = 1;
TM_IeCO5P1bEFfytAeZMzA9bFg_0[2].offset = offsetof(tyTuple_47w2DboNEPf69aPgubZdd7Q, Field1);
TM_IeCO5P1bEFfytAeZMzA9bFg_0[2].typ = (&NTI_Oicxd75j1oQ6Xr53IdlvoA_);
TM_IeCO5P1bEFfytAeZMzA9bFg_0[2].name = "Field1";
TM_IeCO5P1bEFfytAeZMzA9bFg_151[2] = &TM_IeCO5P1bEFfytAeZMzA9bFg_0[3];
TM_IeCO5P1bEFfytAeZMzA9bFg_0[3].kind = 1;
TM_IeCO5P1bEFfytAeZMzA9bFg_0[3].offset = offsetof(tyTuple_47w2DboNEPf69aPgubZdd7Q, Field2);
TM_IeCO5P1bEFfytAeZMzA9bFg_0[3].typ = (&NTI_Oicxd75j1oQ6Xr53IdlvoA_);
TM_IeCO5P1bEFfytAeZMzA9bFg_0[3].name = "Field2";
TM_IeCO5P1bEFfytAeZMzA9bFg_0[0].len = 3; TM_IeCO5P1bEFfytAeZMzA9bFg_0[0].kind = 2; TM_IeCO5P1bEFfytAeZMzA9bFg_0[0].sons = &TM_IeCO5P1bEFfytAeZMzA9bFg_151[0];
NTI_47w2DboNEPf69aPgubZdd7Q_.node = &TM_IeCO5P1bEFfytAeZMzA9bFg_0[0];
}

