/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:   gcc -c  -w -pthread -g3 -O0 -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/user/Dropbox/projects/nim/stui/nimcache/stdlib_terminal.o /home/user/Dropbox/projects/nim/stui/nimcache/stdlib_terminal.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <unistd.h>
#include <termios.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;typedef struct TGenericSeq TGenericSeq;typedef struct tyTuple_47w2DboNEPf69aPgubZdd7Q tyTuple_47w2DboNEPf69aPgubZdd7Q;typedef struct TNimType TNimType;typedef struct TNimNode TNimNode;typedef struct tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA;typedef NU8 tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA;struct TGenericSeq {NI len;NI reserved;};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];};
typedef NU8 tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg;struct tyTuple_47w2DboNEPf69aPgubZdd7Q {NI Field0;NI Field1;NI Field2;};
typedef NU8 tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA;typedef NU8 tyEnum_Style_NXKayqTLMsAibFwNceBlpA;typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);struct TNimType {NI size;tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;TNimType* base;TNimNode* node;void* finalizer;tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;};
struct tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA {unsigned short ws_row;unsigned short ws_col;unsigned short ws_xpixel;unsigned short ws_ypixel;};
typedef NI tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw[3];typedef NI tyArray_GAcaPw08Gj9cXYhAaMMr9cfw[1];typedef unsigned char tyArray_wo9atxlj1CQKWeAypuYX9cIg[32];typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;struct TNimNode {tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;NI offset;TNimType* typ;NCSTRING name;NI len;TNimNode** sons;};

#line 319 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "/usr/lib/nim/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 110 "/usr/lib/nim/system/sysio.nim"
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
#line 490 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ)(NI style);
#line 69 "/usr/lib/nim/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
#line 1293 "/usr/lib/nim/system.nim"
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
#line 218 "/usr/lib/nim/system/sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
#line 3241 "/usr/lib/nim/system.nim"
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
#line 207 "/usr/lib/nim/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
#line 305 "/usr/lib/nim/system/sysstr.nim"
N_LIB_PRIVATE N_NIMCALL(void, add_IbYQ9cTcoQ89aIwM2IEYGMng)(NimStringDesc** result, NI64 x);
#line 107 "/usr/lib/nim/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
#line 417 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 412 "/usr/lib/nim/system/excpt.nim"
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 70 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 612 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getBGColorStr_JQuRsZwRGgtcto9at4yRYqw)(NI color);
#line 53 "/usr/lib/nim/pure/colors.nim"
N_LIB_PRIVATE N_NIMCALL(tyTuple_47w2DboNEPf69aPgubZdd7Q, extractRGB_BBeGhczeu0Oe9b4tbckVIHA)(NI a);
#line 600 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getFGColorStr_JQuRsZwRGgtcto9at4yRYqw_2)(NI color);
#line 30 "/usr/lib/nim/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "/usr/lib/nim/system/chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 222 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0);
#line 18 "/usr/lib/nim/system/chcks.nim"
N_NOINLINE(void, raiseIndexError)(void);
#line 77 "/usr/lib/nim/system/sysstr.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 1285 "/usr/lib/nim/system.nim"
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
#line 97 "/usr/lib/nim/pure/includes/osenv.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
#line 259 "/usr/lib/nim/pure/parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
#line 231 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2)(NI* fds, NI fdsLen_0);
#line 463 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_3)(FILE* f);
#line 142 "/usr/lib/nim/system/sysio.nim"
N_LIB_PRIVATE N_NIMCALL(int, getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg)(FILE* f);
#line 210 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setRaw_bWuPmHcnrBG1QQlDC4s7ug)(int fd, int time_0);
#line 134 "/usr/lib/nim/system/sysio.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar_ufPUIQ2Rg4xhWjWigciDOg)(FILE* f);
#line 2423 "/usr/lib/nim/system.nim"
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwterminal_extra)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
#line 2415 "/usr/lib/nim/system.nim"
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQterminal_extra)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
#line 35 "/usr/lib/nim/system/sysstr.nim"
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
#line 3249 "/usr/lib/nim/system.nim"
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQstui)(void* a, void* b, NI size);
#line 212 "/usr/lib/nim/pure/strutils.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);NIM_BOOL trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;NIM_BOOL trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ;NIM_BOOL fgSetColor_az9a3BILKewIOic9a2Ah9a4tQ;NIM_THREADVAR NI gFG_g7w4T3anr20OMlWloNx2tQ;NIM_THREADVAR NI gBG_dgmeknpHWrtwqMJGQAp9atA;extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;TNimType NTI_NXKayqTLMsAibFwNceBlpA_;STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_3, "\033[", 2);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_4, "m", 1);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_6, "\033[48;2;", 7);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_7, ";", 1);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_8, "\033[38;2;", 7);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_10, "f", 1);NIM_CONST tyArray_Bd4h7Ocx9bGTvrKzPIWNlHw TM_CN3raB9atujkEiPpxYAdlgQ_15 = {((NI) 0),((NI) 1),((NI) 2)};STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_16, "COLUMNS", 7);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_17, "", 0);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_19, "LINES", 5);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_20, "\033[\?25l", 6);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_21, "\033[\?25h", 6);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_22, "\033[0m", 4);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_26, "truecolor", 9);STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_27, "24bit", 5);NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_CN3raB9atujkEiPpxYAdlgQ_25 = {((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_26),((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_27)};STRING_LITERAL(TM_CN3raB9atujkEiPpxYAdlgQ_28, "COLORTERM", 9);

#line 319 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 320 "/usr/lib/nim/system/arithm.nim"

#line 320 "/usr/lib/nim/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/usr/lib/nim/system/arithm.nim"
	{		NIM_BOOL T3_;
#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 321 "/usr/lib/nim/system/arithm.nim"

#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 321 "/usr/lib/nim/system/arithm.nim"

#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ b));		LA4_: ;		if (!T3_) goto LA5_;
#line 322 "/usr/lib/nim/system/arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 323 "/usr/lib/nim/system/arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 3241 "/usr/lib/nim/system.nim"
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
#line 3242 "/usr/lib/nim/system.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}


#line 218 "/usr/lib/nim/system/sysstr.nim"
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {

#line 219 "/usr/lib/nim/system/sysstr.nim"

#line 219 "/usr/lib/nim/system/sysstr.nim"
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
#line 220 "/usr/lib/nim/system/sysstr.nim"
	(*dest).Sup.len += (*src).Sup.len;}


#line 417 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
#line 418 "/usr/lib/nim/system/excpt.nim"
	T1_ = (NI)0;
#line 418 "/usr/lib/nim/system/excpt.nim"
	{
#line 418 "/usr/lib/nim/system/excpt.nim"
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;		T1_ = ((NI) 0);	}	goto LA2_;	LA4_: ;	{
#line 418 "/usr/lib/nim/system/excpt.nim"
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}	LA2_: ;	(*s).calldepth = ((NI16) (T1_));
#line 419 "/usr/lib/nim/system/excpt.nim"
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 420 "/usr/lib/nim/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 421 "/usr/lib/nim/system/excpt.nim"
	{
#line 421 "/usr/lib/nim/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
#line 421 "/usr/lib/nim/system/excpt.nim"
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();	}	LA9_: ;}


#line 70 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 71 "/usr/lib/nim/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}


#line 490 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ)(NI style) {
	NimStringDesc* result;	NimStringDesc* fmtRes;	nimfr_("getStyleStr", "terminal.nim");	result = (NimStringDesc*)0;
#line 492 "/usr/lib/nim/pure/terminal.nim"
	nimln_(492, "terminal.nim");
#line 492 "/usr/lib/nim/pure/terminal.nim"

#line 492 "/usr/lib/nim/pure/terminal.nim"
	fmtRes = rawNewString(((NI) 41));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	nimln_(313, "strformat.nim");	fmtRes = resizeString(fmtRes, 2);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_3));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (style)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_4));	result = copyString(fmtRes);	popFrame();	return result;}


#line 577 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor_6SjySiY3ji4zTKKPgtXoig)(FILE* f, tyEnum_BackgroundColor_7jPyx0xRLWzxER9cSeCOA9bA bg, NIM_BOOL bright) {
	NimStringDesc* T5_;	nimfr_("setBackgroundColor", "terminal.nim");
#line 595 "/usr/lib/nim/pure/terminal.nim"
	nimln_(595, "terminal.nim");
#line 595 "/usr/lib/nim/pure/terminal.nim"
	gBG_dgmeknpHWrtwqMJGQAp9atA = bg;
#line 596 "/usr/lib/nim/pure/terminal.nim"
	nimln_(596, "terminal.nim");	{		NI TM_CN3raB9atujkEiPpxYAdlgQ_2;		if (!bright) goto LA3_;
#line 596 "/usr/lib/nim/pure/terminal.nim"
		TM_CN3raB9atujkEiPpxYAdlgQ_2 = addInt(gBG_dgmeknpHWrtwqMJGQAp9atA, ((NI) 60));		gBG_dgmeknpHWrtwqMJGQAp9atA = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_2);	}	LA3_: ;
#line 597 "/usr/lib/nim/pure/terminal.nim"
	nimln_(597, "terminal.nim");
#line 597 "/usr/lib/nim/pure/terminal.nim"
	T5_ = (NimStringDesc*)0;	T5_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(gBG_dgmeknpHWrtwqMJGQAp9atA);	write_c4mGyJBvK73pdM22jiweKQ(f, T5_);	popFrame();}


#line 555 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_Tw7yxMupneOmAicqiYt3NA)(FILE* f, tyEnum_ForegroundColor_ez9ah4IgQc0AbdW68acioDg fg, NIM_BOOL bright) {
	NimStringDesc* T5_;	nimfr_("setForegroundColor", "terminal.nim");
#line 573 "/usr/lib/nim/pure/terminal.nim"
	nimln_(573, "terminal.nim");
#line 573 "/usr/lib/nim/pure/terminal.nim"
	gFG_g7w4T3anr20OMlWloNx2tQ = fg;
#line 574 "/usr/lib/nim/pure/terminal.nim"
	nimln_(574, "terminal.nim");	{		NI TM_CN3raB9atujkEiPpxYAdlgQ_5;		if (!bright) goto LA3_;
#line 574 "/usr/lib/nim/pure/terminal.nim"
		TM_CN3raB9atujkEiPpxYAdlgQ_5 = addInt(gFG_g7w4T3anr20OMlWloNx2tQ, ((NI) 60));		gFG_g7w4T3anr20OMlWloNx2tQ = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_5);	}	LA3_: ;
#line 575 "/usr/lib/nim/pure/terminal.nim"
	nimln_(575, "terminal.nim");
#line 575 "/usr/lib/nim/pure/terminal.nim"
	T5_ = (NimStringDesc*)0;	T5_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(gFG_g7w4T3anr20OMlWloNx2tQ);	write_c4mGyJBvK73pdM22jiweKQ(f, T5_);	popFrame();}


#line 612 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getBGColorStr_JQuRsZwRGgtcto9at4yRYqw)(NI color) {
	NimStringDesc* result;	tyTuple_47w2DboNEPf69aPgubZdd7Q rgb;	NimStringDesc* fmtRes;	nimfr_("getBGColorStr", "terminal.nim");	result = (NimStringDesc*)0;
#line 614 "/usr/lib/nim/pure/terminal.nim"
	nimln_(614, "terminal.nim");	rgb = extractRGB_BBeGhczeu0Oe9b4tbckVIHA(color);
#line 615 "/usr/lib/nim/pure/terminal.nim"
	nimln_(615, "terminal.nim");
#line 615 "/usr/lib/nim/pure/terminal.nim"

#line 615 "/usr/lib/nim/pure/terminal.nim"
	fmtRes = rawNewString(((NI) 74));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	nimln_(313, "strformat.nim");	fmtRes = resizeString(fmtRes, 7);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_6));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field0)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field1)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field2)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_4));	result = copyString(fmtRes);	popFrame();	return result;}


#line 629 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setBackgroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA)(FILE* f, NI color) {
	nimfr_("setBackgroundColor", "terminal.nim");
#line 631 "/usr/lib/nim/pure/terminal.nim"
	nimln_(631, "terminal.nim");	{		NimStringDesc* T5_;		if (!trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ) goto LA3_;
#line 632 "/usr/lib/nim/pure/terminal.nim"
		nimln_(632, "terminal.nim");
#line 632 "/usr/lib/nim/pure/terminal.nim"
		T5_ = (NimStringDesc*)0;		T5_ = getBGColorStr_JQuRsZwRGgtcto9at4yRYqw(color);		write_c4mGyJBvK73pdM22jiweKQ(f, T5_);	}	LA3_: ;	popFrame();}


#line 600 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getFGColorStr_JQuRsZwRGgtcto9at4yRYqw_2)(NI color) {
	NimStringDesc* result;	tyTuple_47w2DboNEPf69aPgubZdd7Q rgb;	NimStringDesc* fmtRes;	nimfr_("getFGColorStr", "terminal.nim");	result = (NimStringDesc*)0;
#line 602 "/usr/lib/nim/pure/terminal.nim"
	nimln_(602, "terminal.nim");	rgb = extractRGB_BBeGhczeu0Oe9b4tbckVIHA(color);
#line 603 "/usr/lib/nim/pure/terminal.nim"
	nimln_(603, "terminal.nim");
#line 603 "/usr/lib/nim/pure/terminal.nim"

#line 603 "/usr/lib/nim/pure/terminal.nim"
	fmtRes = rawNewString(((NI) 74));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	nimln_(313, "strformat.nim");	fmtRes = resizeString(fmtRes, 7);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_8));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field0)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field1)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (rgb.Field2)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_4));	result = copyString(fmtRes);	popFrame();	return result;}


#line 624 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setForegroundColor_cUJ3dLt9bYXmlU3lm9a8z5lA_2)(FILE* f, NI color) {
	nimfr_("setForegroundColor", "terminal.nim");
#line 626 "/usr/lib/nim/pure/terminal.nim"
	nimln_(626, "terminal.nim");	{		NimStringDesc* T5_;		if (!trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ) goto LA3_;
#line 627 "/usr/lib/nim/pure/terminal.nim"
		nimln_(627, "terminal.nim");
#line 627 "/usr/lib/nim/pure/terminal.nim"
		T5_ = (NimStringDesc*)0;		T5_ = getFGColorStr_JQuRsZwRGgtcto9at4yRYqw_2(color);		write_c4mGyJBvK73pdM22jiweKQ(f, T5_);	}	LA3_: ;	popFrame();}


#line 30 "/usr/lib/nim/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;{	result = (NI)0;
#line 31 "/usr/lib/nim/system/chcks.nim"
	{		NIM_BOOL T3_;
#line 31 "/usr/lib/nim/system/chcks.nim"
		T3_ = (NIM_BOOL)0;
#line 31 "/usr/lib/nim/system/chcks.nim"
		T3_ = (a <= i);		if (!(T3_)) goto LA4_;
#line 31 "/usr/lib/nim/system/chcks.nim"
		T3_ = (i <= b);		LA4_: ;		if (!T3_) goto LA5_;
#line 32 "/usr/lib/nim/system/chcks.nim"

#line 32 "/usr/lib/nim/system/chcks.nim"
		result = i;		goto BeforeRet_;	}	goto LA1_;	LA5_: ;	{
#line 34 "/usr/lib/nim/system/chcks.nim"
		raiseRangeError(((NI64) (i)));	}	LA1_: ;	}BeforeRet_: ;	return result;}


#line 500 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setStyle_zEKKPPIjKZs9bVYu4TwenLg)(FILE* f, tySet_tyEnum_Style_NXKayqTLMsAibFwNceBlpA style) {
	nimfr_("setStyle", "terminal.nim");	{		tyEnum_Style_NXKayqTLMsAibFwNceBlpA s;		NI i;		s = (tyEnum_Style_NXKayqTLMsAibFwNceBlpA)0;
#line 2219 "/usr/lib/nim/system.nim"
		nimln_(2219, "system.nim");		i = ((NI) 1);		{
#line 2220 "/usr/lib/nim/system.nim"
			nimln_(2220, "system.nim");			while (1) {				NI TM_CN3raB9atujkEiPpxYAdlgQ_9;
#line 2220 "/usr/lib/nim/system.nim"
				if (!(i <= ((NI) 8))) goto LA3;
#line 2221 "/usr/lib/nim/system.nim"
				nimln_(2221, "system.nim");				{					NimStringDesc* T8_;
#line 2221 "/usr/lib/nim/system.nim"
					if (!((style &(1U<<((NU)((((tyEnum_Style_NXKayqTLMsAibFwNceBlpA)chckRange(i, ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 1), ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 8)))- 1))&7U)))!=0)) goto LA6_;
#line 2221 "/usr/lib/nim/system.nim"
					s = ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA)chckRange(i, ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 1), ((tyEnum_Style_NXKayqTLMsAibFwNceBlpA) 8)));
#line 513 "/usr/lib/nim/pure/terminal.nim"
					nimln_(513, "terminal.nim");
#line 513 "/usr/lib/nim/pure/terminal.nim"

#line 513 "/usr/lib/nim/pure/terminal.nim"
					T8_ = (NimStringDesc*)0;					T8_ = getStyleStr_bfu8TiCl9avGVg9csJBAYIRQ(s);					write_c4mGyJBvK73pdM22jiweKQ(f, T8_);				}				LA6_: ;
#line 2222 "/usr/lib/nim/system.nim"
				nimln_(2222, "system.nim");				TM_CN3raB9atujkEiPpxYAdlgQ_9 = addInt(i, ((NI) 1));				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_9);			} LA3: ;		}	}	popFrame();}


#line 306 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setCursorPos_UIoIgoUReHcDarvfaNRl3A)(FILE* f, NI x, NI y) {
	NimStringDesc* fmtRes;	nimfr_("setCursorPos", "terminal.nim");
#line 313 "/usr/lib/nim/pure/terminal.nim"
	nimln_(313, "terminal.nim");
#line 313 "/usr/lib/nim/pure/terminal.nim"

#line 313 "/usr/lib/nim/pure/terminal.nim"
	fmtRes = rawNewString(((NI) 51));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	nimln_(313, "strformat.nim");	fmtRes = resizeString(fmtRes, 2);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_3));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (y)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_7));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	add_IbYQ9cTcoQ89aIwM2IEYGMng((&fmtRes), ((NI64) (x)));
#line 313 "/usr/lib/nim/pure/strformat.nim"
	fmtRes = resizeString(fmtRes, 1);appendString(fmtRes, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_10));	write_c4mGyJBvK73pdM22jiweKQ(f, fmtRes);	popFrame();}


#line 222 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ)(NI* fds, NI fdsLen_0) {
	NI result;	tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;	nimfr_("terminalWidthIoctl", "terminal.nim");{	result = (NI)0;	memset((void*)(&win), 0, sizeof(win));	{		NI fd;		NI i;		fd = (NI)0;
#line 2185 "/usr/lib/nim/system.nim"
		nimln_(2185, "system.nim");		i = ((NI) 0);		{
#line 2186 "/usr/lib/nim/system.nim"
			nimln_(2186, "system.nim");			while (1) {				NI TM_CN3raB9atujkEiPpxYAdlgQ_14;
#line 2186 "/usr/lib/nim/system.nim"

#line 2186 "/usr/lib/nim/system.nim"
				if (!(i < fdsLen_0)) goto LA3;
#line 2187 "/usr/lib/nim/system.nim"
				nimln_(2187, "system.nim");				if ((NU)(i) >= (NU)(fdsLen_0)) raiseIndexError();				fd = fds[i];
#line 227 "/usr/lib/nim/pure/terminal.nim"
				nimln_(227, "terminal.nim");				{					NI T6_;
#line 398 "/usr/lib/nim/system.nim"
					nimln_(398, "system.nim");
#line 227 "/usr/lib/nim/pure/terminal.nim"
					nimln_(227, "terminal.nim");
#line 227 "/usr/lib/nim/pure/terminal.nim"
					T6_ = (NI)0;					T6_ = ioctl(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), TIOCGWINSZ, (&win));					if (!!((T6_ == ((NI) -1)))) goto LA7_;
#line 228 "/usr/lib/nim/pure/terminal.nim"
					nimln_(228, "terminal.nim");
#line 228 "/usr/lib/nim/pure/terminal.nim"
					result = ((NI) (win.ws_col));					goto BeforeRet_;				}				LA7_: ;
#line 2188 "/usr/lib/nim/system.nim"
				nimln_(2188, "system.nim");				TM_CN3raB9atujkEiPpxYAdlgQ_14 = addInt(i, ((NI) 1));				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_14);			} LA3: ;		}	}
#line 229 "/usr/lib/nim/pure/terminal.nim"
	nimln_(229, "terminal.nim");
#line 229 "/usr/lib/nim/pure/terminal.nim"
	result = ((NI) 0);	goto BeforeRet_;	}BeforeRet_: ;	popFrame();	return result;}


#line 242 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NI, terminalWidth_Tjr5MOdj42hdx5sjNUiDXw)(void) {
	NI result;	NI w;	NimStringDesc* cterm;	int fd;	NCSTRING T5_;	int T11_;	NimStringDesc* s;	nimfr_("terminalWidth", "terminal.nim");{	result = (NI)0;
#line 246 "/usr/lib/nim/pure/terminal.nim"
	nimln_(246, "terminal.nim");	w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(TM_CN3raB9atujkEiPpxYAdlgQ_15, 3);
#line 247 "/usr/lib/nim/pure/terminal.nim"
	nimln_(247, "terminal.nim");	{
#line 247 "/usr/lib/nim/pure/terminal.nim"
		if (!(((NI) 0) < w)) goto LA3_;
#line 247 "/usr/lib/nim/pure/terminal.nim"

#line 247 "/usr/lib/nim/pure/terminal.nim"
		result = w;		goto BeforeRet_;	}	LA3_: ;
#line 248 "/usr/lib/nim/pure/terminal.nim"
	nimln_(248, "terminal.nim");
#line 248 "/usr/lib/nim/pure/terminal.nim"
	cterm = mnewString(((NI)chckRange(L_ctermid, ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 249 "/usr/lib/nim/pure/terminal.nim"
	nimln_(249, "terminal.nim");
#line 249 "/usr/lib/nim/pure/terminal.nim"
	T5_ = (NCSTRING)0;	T5_ = ctermid(cterm->data);	fd = open(T5_, ((int) 0));
#line 250 "/usr/lib/nim/pure/terminal.nim"
	nimln_(250, "terminal.nim");	{		tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
#line 398 "/usr/lib/nim/system.nim"
		nimln_(398, "system.nim");
#line 250 "/usr/lib/nim/pure/terminal.nim"
		nimln_(250, "terminal.nim");		if (!!((fd == ((NI32) -1)))) goto LA8_;
#line 251 "/usr/lib/nim/pure/terminal.nim"
		nimln_(251, "terminal.nim");		T10_[0] = ((NI) (fd));		w = terminalWidthIoctl_u2BBS9b3k8WyoyVOocOs5YQ(T10_, 1);	}	LA8_: ;
#line 252 "/usr/lib/nim/pure/terminal.nim"
	nimln_(252, "terminal.nim");	T11_ = (int)0;	T11_ = close(fd);	T11_;

#line 253 "/usr/lib/nim/pure/terminal.nim"
	nimln_(253, "terminal.nim");	{
#line 253 "/usr/lib/nim/pure/terminal.nim"
		if (!(((NI) 0) < w)) goto LA14_;
#line 253 "/usr/lib/nim/pure/terminal.nim"

#line 253 "/usr/lib/nim/pure/terminal.nim"
		result = w;		goto BeforeRet_;	}	LA14_: ;
#line 254 "/usr/lib/nim/pure/terminal.nim"
	nimln_(254, "terminal.nim");	s = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_16), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_17));
#line 255 "/usr/lib/nim/pure/terminal.nim"
	nimln_(255, "terminal.nim");	{		NIM_BOOL T18_;		NIM_BOOL T19_;		NI T21_;
#line 255 "/usr/lib/nim/pure/terminal.nim"
		T18_ = (NIM_BOOL)0;
#line 255 "/usr/lib/nim/pure/terminal.nim"
		T19_ = (NIM_BOOL)0;
#line 255 "/usr/lib/nim/pure/terminal.nim"

#line 255 "/usr/lib/nim/pure/terminal.nim"
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));		if (!(T19_)) goto LA20_;
#line 255 "/usr/lib/nim/pure/terminal.nim"

#line 255 "/usr/lib/nim/pure/terminal.nim"
		T21_ = (NI)0;		T21_ = npuParseInt(s, (&w), ((NI) 0));		T19_ = (((NI) 0) < T21_);		LA20_: ;		T18_ = T19_;		if (!(T18_)) goto LA22_;
#line 255 "/usr/lib/nim/pure/terminal.nim"
		T18_ = (((NI) 0) < w);		LA22_: ;		if (!T18_) goto LA23_;
#line 256 "/usr/lib/nim/pure/terminal.nim"
		nimln_(256, "terminal.nim");
#line 256 "/usr/lib/nim/pure/terminal.nim"
		result = w;		goto BeforeRet_;	}	LA23_: ;
#line 257 "/usr/lib/nim/pure/terminal.nim"
	nimln_(257, "terminal.nim");
#line 257 "/usr/lib/nim/pure/terminal.nim"
	result = ((NI) 80);	goto BeforeRet_;	}BeforeRet_: ;	popFrame();	return result;}


#line 231 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2)(NI* fds, NI fdsLen_0) {
	NI result;	tyObject_IOctl_WinSize_pb6i9aLcdojBXEMqdEzDkSA win;	nimfr_("terminalHeightIoctl", "terminal.nim");{	result = (NI)0;	memset((void*)(&win), 0, sizeof(win));	{		NI fd;		NI i;		fd = (NI)0;
#line 2185 "/usr/lib/nim/system.nim"
		nimln_(2185, "system.nim");		i = ((NI) 0);		{
#line 2186 "/usr/lib/nim/system.nim"
			nimln_(2186, "system.nim");			while (1) {				NI TM_CN3raB9atujkEiPpxYAdlgQ_18;
#line 2186 "/usr/lib/nim/system.nim"

#line 2186 "/usr/lib/nim/system.nim"
				if (!(i < fdsLen_0)) goto LA3;
#line 2187 "/usr/lib/nim/system.nim"
				nimln_(2187, "system.nim");				if ((NU)(i) >= (NU)(fdsLen_0)) raiseIndexError();				fd = fds[i];
#line 236 "/usr/lib/nim/pure/terminal.nim"
				nimln_(236, "terminal.nim");				{					NI T6_;
#line 398 "/usr/lib/nim/system.nim"
					nimln_(398, "system.nim");
#line 236 "/usr/lib/nim/pure/terminal.nim"
					nimln_(236, "terminal.nim");
#line 236 "/usr/lib/nim/pure/terminal.nim"
					T6_ = (NI)0;					T6_ = ioctl(((int)chckRange(fd, ((int) (-2147483647 -1)), ((int) 2147483647))), TIOCGWINSZ, (&win));					if (!!((T6_ == ((NI) -1)))) goto LA7_;
#line 237 "/usr/lib/nim/pure/terminal.nim"
					nimln_(237, "terminal.nim");
#line 237 "/usr/lib/nim/pure/terminal.nim"
					result = ((NI) (win.ws_row));					goto BeforeRet_;				}				LA7_: ;
#line 2188 "/usr/lib/nim/system.nim"
				nimln_(2188, "system.nim");				TM_CN3raB9atujkEiPpxYAdlgQ_18 = addInt(i, ((NI) 1));				i = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_18);			} LA3: ;		}	}
#line 238 "/usr/lib/nim/pure/terminal.nim"
	nimln_(238, "terminal.nim");
#line 238 "/usr/lib/nim/pure/terminal.nim"
	result = ((NI) 0);	goto BeforeRet_;	}BeforeRet_: ;	popFrame();	return result;}


#line 259 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NI, terminalHeight_Tjr5MOdj42hdx5sjNUiDXw_2)(void) {
	NI result;	NI h;	NimStringDesc* cterm;	int fd;	NCSTRING T5_;	int T11_;	NimStringDesc* s;	nimfr_("terminalHeight", "terminal.nim");{	result = (NI)0;
#line 264 "/usr/lib/nim/pure/terminal.nim"
	nimln_(264, "terminal.nim");	h = terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2(TM_CN3raB9atujkEiPpxYAdlgQ_15, 3);
#line 265 "/usr/lib/nim/pure/terminal.nim"
	nimln_(265, "terminal.nim");	{
#line 265 "/usr/lib/nim/pure/terminal.nim"
		if (!(((NI) 0) < h)) goto LA3_;
#line 265 "/usr/lib/nim/pure/terminal.nim"

#line 265 "/usr/lib/nim/pure/terminal.nim"
		result = h;		goto BeforeRet_;	}	LA3_: ;
#line 266 "/usr/lib/nim/pure/terminal.nim"
	nimln_(266, "terminal.nim");
#line 266 "/usr/lib/nim/pure/terminal.nim"
	cterm = mnewString(((NI)chckRange(L_ctermid, ((NI) 0), ((NI) IL64(9223372036854775807)))));
#line 267 "/usr/lib/nim/pure/terminal.nim"
	nimln_(267, "terminal.nim");
#line 267 "/usr/lib/nim/pure/terminal.nim"
	T5_ = (NCSTRING)0;	T5_ = ctermid(cterm->data);	fd = open(T5_, ((int) 0));
#line 268 "/usr/lib/nim/pure/terminal.nim"
	nimln_(268, "terminal.nim");	{		tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T10_;
#line 398 "/usr/lib/nim/system.nim"
		nimln_(398, "system.nim");
#line 268 "/usr/lib/nim/pure/terminal.nim"
		nimln_(268, "terminal.nim");		if (!!((fd == ((NI32) -1)))) goto LA8_;
#line 269 "/usr/lib/nim/pure/terminal.nim"
		nimln_(269, "terminal.nim");		T10_[0] = ((NI) (fd));		h = terminalHeightIoctl_u2BBS9b3k8WyoyVOocOs5YQ_2(T10_, 1);	}	LA8_: ;
#line 270 "/usr/lib/nim/pure/terminal.nim"
	nimln_(270, "terminal.nim");	T11_ = (int)0;	T11_ = close(fd);	T11_;

#line 271 "/usr/lib/nim/pure/terminal.nim"
	nimln_(271, "terminal.nim");	{
#line 271 "/usr/lib/nim/pure/terminal.nim"
		if (!(((NI) 0) < h)) goto LA14_;
#line 271 "/usr/lib/nim/pure/terminal.nim"

#line 271 "/usr/lib/nim/pure/terminal.nim"
		result = h;		goto BeforeRet_;	}	LA14_: ;
#line 272 "/usr/lib/nim/pure/terminal.nim"
	nimln_(272, "terminal.nim");	s = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_19), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_17));
#line 273 "/usr/lib/nim/pure/terminal.nim"
	nimln_(273, "terminal.nim");	{		NIM_BOOL T18_;		NIM_BOOL T19_;		NI T21_;
#line 273 "/usr/lib/nim/pure/terminal.nim"
		T18_ = (NIM_BOOL)0;
#line 273 "/usr/lib/nim/pure/terminal.nim"
		T19_ = (NIM_BOOL)0;
#line 273 "/usr/lib/nim/pure/terminal.nim"

#line 273 "/usr/lib/nim/pure/terminal.nim"
		T19_ = (((NI) 0) < (s ? s->Sup.len : 0));		if (!(T19_)) goto LA20_;
#line 273 "/usr/lib/nim/pure/terminal.nim"

#line 273 "/usr/lib/nim/pure/terminal.nim"
		T21_ = (NI)0;		T21_ = npuParseInt(s, (&h), ((NI) 0));		T19_ = (((NI) 0) < T21_);		LA20_: ;		T18_ = T19_;		if (!(T18_)) goto LA22_;
#line 273 "/usr/lib/nim/pure/terminal.nim"
		T18_ = (((NI) 0) < h);		LA22_: ;		if (!T18_) goto LA23_;
#line 274 "/usr/lib/nim/pure/terminal.nim"
		nimln_(274, "terminal.nim");
#line 274 "/usr/lib/nim/pure/terminal.nim"
		result = h;		goto BeforeRet_;	}	LA23_: ;
#line 275 "/usr/lib/nim/pure/terminal.nim"
	nimln_(275, "terminal.nim");
#line 275 "/usr/lib/nim/pure/terminal.nim"
	result = ((NI) 0);	goto BeforeRet_;	}BeforeRet_: ;	popFrame();	return result;}


#line 292 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, hideCursor_tFIu39aFSR3N0M64Ynwugng)(FILE* f) {
	nimfr_("hideCursor", "terminal.nim");
#line 297 "/usr/lib/nim/pure/terminal.nim"
	nimln_(297, "terminal.nim");	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_20));	popFrame();}


#line 299 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, showCursor_tFIu39aFSR3N0M64Ynwugng_2)(FILE* f) {
	nimfr_("showCursor", "terminal.nim");
#line 304 "/usr/lib/nim/pure/terminal.nim"
	nimln_(304, "terminal.nim");	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_21));	popFrame();}


#line 463 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, resetAttributes_tFIu39aFSR3N0M64Ynwugng_3)(FILE* f) {
	nimfr_("resetAttributes", "terminal.nim");
#line 471 "/usr/lib/nim/pure/terminal.nim"
	nimln_(471, "terminal.nim");	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_22));	popFrame();}


#line 812 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NOCONV(void, resetAttributes_1y1Orb5p0KBhRdFFLR9bNtg)(void) {
	nimfr_("resetAttributes", "terminal.nim");
#line 816 "/usr/lib/nim/pure/terminal.nim"
	nimln_(816, "terminal.nim");	resetAttributes_tFIu39aFSR3N0M64Ynwugng_3(stdout);	popFrame();}


#line 210 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, setRaw_bWuPmHcnrBG1QQlDC4s7ug)(int fd, int time_0) {
	struct termios mode;	int T1_;	int T2_;	nimfr_("setRaw", "terminal.nim");	memset((void*)(&mode), 0, sizeof(mode));
#line 212 "/usr/lib/nim/pure/terminal.nim"
	nimln_(212, "terminal.nim");	T1_ = (int)0;	T1_ = tcgetattr(fd, (&mode));	T1_;

#line 213 "/usr/lib/nim/pure/terminal.nim"
	nimln_(213, "terminal.nim");
#line 213 "/usr/lib/nim/pure/terminal.nim"

#line 213 "/usr/lib/nim/pure/terminal.nim"

#line 213 "/usr/lib/nim/pure/terminal.nim"

#line 213 "/usr/lib/nim/pure/terminal.nim"

#line 213 "/usr/lib/nim/pure/terminal.nim"

#line 213 "/usr/lib/nim/pure/terminal.nim"
	mode.c_iflag = (NU32)(mode.c_iflag & (NU32)((NU32) ~((NU32)((NU32)((NU32)((NU32)(BRKINT | ICRNL) | INPCK) | ISTRIP) | IXON))));
#line 215 "/usr/lib/nim/pure/terminal.nim"
	nimln_(215, "terminal.nim");
#line 215 "/usr/lib/nim/pure/terminal.nim"

#line 215 "/usr/lib/nim/pure/terminal.nim"
	mode.c_oflag = (NU32)(mode.c_oflag & (NU32)((NU32) ~(OPOST)));
#line 216 "/usr/lib/nim/pure/terminal.nim"
	nimln_(216, "terminal.nim");
#line 216 "/usr/lib/nim/pure/terminal.nim"

#line 216 "/usr/lib/nim/pure/terminal.nim"

#line 216 "/usr/lib/nim/pure/terminal.nim"

#line 216 "/usr/lib/nim/pure/terminal.nim"
	mode.c_cflag = (NU32)((NU32)(mode.c_cflag & (NU32)((NU32) ~((NU32)(CSIZE | PARENB)))) | CS8);
#line 217 "/usr/lib/nim/pure/terminal.nim"
	nimln_(217, "terminal.nim");
#line 217 "/usr/lib/nim/pure/terminal.nim"

#line 217 "/usr/lib/nim/pure/terminal.nim"

#line 217 "/usr/lib/nim/pure/terminal.nim"

#line 217 "/usr/lib/nim/pure/terminal.nim"

#line 217 "/usr/lib/nim/pure/terminal.nim"
	mode.c_lflag = (NU32)(mode.c_lflag & (NU32)((NU32) ~((NU32)((NU32)((NU32)(ECHO | ICANON) | IEXTEN) | ISIG))));	if ((NU)(VMIN) > (NU)(31)) raiseIndexError();
#line 218 "/usr/lib/nim/pure/terminal.nim"
	nimln_(218, "terminal.nim");	mode.c_cc[(VMIN)- 0] = 1;	if ((NU)(VTIME) > (NU)(31)) raiseIndexError();
#line 219 "/usr/lib/nim/pure/terminal.nim"
	nimln_(219, "terminal.nim");	mode.c_cc[(VTIME)- 0] = 0;
#line 220 "/usr/lib/nim/pure/terminal.nim"
	nimln_(220, "terminal.nim");	T2_ = (int)0;	T2_ = tcsetattr(fd, time_0, (&mode));	T2_;
	popFrame();}


#line 717 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, getch_PZUNldkwV2VhZMU6UCrZTA)(void) {
	NIM_CHAR result;	int fd;	struct termios oldMode;	int T1_;	int T2_;	nimfr_("getch", "terminal.nim");	result = (NIM_CHAR)0;
#line 732 "/usr/lib/nim/pure/terminal.nim"
	nimln_(732, "terminal.nim");	fd = getFileHandle_bZ9c2yojtXoDTUpfyl8h8Rg(stdin);	memset((void*)(&oldMode), 0, sizeof(oldMode));
#line 734 "/usr/lib/nim/pure/terminal.nim"
	nimln_(734, "terminal.nim");	T1_ = (int)0;	T1_ = tcgetattr(fd, (&oldMode));	T1_;

#line 735 "/usr/lib/nim/pure/terminal.nim"
	nimln_(735, "terminal.nim");	setRaw_bWuPmHcnrBG1QQlDC4s7ug(fd, TCSAFLUSH);
#line 736 "/usr/lib/nim/pure/terminal.nim"
	nimln_(736, "terminal.nim");	result = readChar_ufPUIQ2Rg4xhWjWigciDOg(stdin);
#line 737 "/usr/lib/nim/pure/terminal.nim"
	nimln_(737, "terminal.nim");	T2_ = (int)0;	T2_ = tcsetattr(fd, TCSADRAIN, (&oldMode));	T2_;
	popFrame();	return result;}


#line 3249 "/usr/lib/nim/system.nim"
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQstui)(void* a, void* b, NI size) {
	NIM_BOOL result;	int T1_;	result = (NIM_BOOL)0;
#line 3250 "/usr/lib/nim/system.nim"

#line 3250 "/usr/lib/nim/system.nim"

#line 3250 "/usr/lib/nim/system.nim"
	T1_ = (int)0;	T1_ = memcmp(a, b, ((size_t) (size)));	result = (T1_ == ((NI32) 0));	return result;}


#line 35 "/usr/lib/nim/system/sysstr.nim"
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;	NIM_BOOL T11_;{	result = (NIM_BOOL)0;
#line 36 "/usr/lib/nim/system/sysstr.nim"
	{
#line 36 "/usr/lib/nim/system/sysstr.nim"
		if (!(a == b)) goto LA3_;
#line 36 "/usr/lib/nim/system/sysstr.nim"

#line 36 "/usr/lib/nim/system/sysstr.nim"
		result = NIM_TRUE;		goto BeforeRet_;	}	LA3_: ;
#line 37 "/usr/lib/nim/system/sysstr.nim"
	{		NIM_BOOL T7_;
#line 37 "/usr/lib/nim/system/sysstr.nim"
		T7_ = (NIM_BOOL)0;
#line 37 "/usr/lib/nim/system/sysstr.nim"
		T7_ = (a == NIM_NIL);		if (T7_) goto LA8_;
#line 37 "/usr/lib/nim/system/sysstr.nim"
		T7_ = (b == NIM_NIL);		LA8_: ;		if (!T7_) goto LA9_;
#line 37 "/usr/lib/nim/system/sysstr.nim"

#line 37 "/usr/lib/nim/system/sysstr.nim"
		result = NIM_FALSE;		goto BeforeRet_;	}	LA9_: ;
#line 38 "/usr/lib/nim/system/sysstr.nim"

#line 38 "/usr/lib/nim/system/sysstr.nim"

#line 38 "/usr/lib/nim/system/sysstr.nim"
	T11_ = (NIM_BOOL)0;
#line 38 "/usr/lib/nim/system/sysstr.nim"
	T11_ = ((*a).Sup.len == (*b).Sup.len);	if (!(T11_)) goto LA12_;
#line 39 "/usr/lib/nim/system/sysstr.nim"
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQstui(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));	LA12_: ;	result = T11_;	goto BeforeRet_;	}BeforeRet_: ;	return result;}


#line 2415 "/usr/lib/nim/system.nim"
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQterminal_extra)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;	nimfr_("find", "system.nim");{	result = (NI)0;	{		NimStringDesc* i;		NI i_2;		i = (NimStringDesc*)0;
#line 2185 "/usr/lib/nim/system.nim"
		nimln_(2185, "system.nim");		i_2 = ((NI) 0);		{
#line 2186 "/usr/lib/nim/system.nim"
			nimln_(2186, "system.nim");			while (1) {				NI TM_CN3raB9atujkEiPpxYAdlgQ_23;				NI TM_CN3raB9atujkEiPpxYAdlgQ_24;
#line 2186 "/usr/lib/nim/system.nim"

#line 2186 "/usr/lib/nim/system.nim"
				if (!(i_2 < aLen_0)) goto LA3;
#line 2187 "/usr/lib/nim/system.nim"
				nimln_(2187, "system.nim");				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();				i = a[i_2];
#line 2419 "/usr/lib/nim/system.nim"
				nimln_(2419, "system.nim");				{
#line 2419 "/usr/lib/nim/system.nim"
					if (!eqStrings(i, item)) goto LA6_;
#line 2419 "/usr/lib/nim/system.nim"
					goto BeforeRet_;				}				LA6_: ;
#line 2420 "/usr/lib/nim/system.nim"
				nimln_(2420, "system.nim");				TM_CN3raB9atujkEiPpxYAdlgQ_23 = addInt(result, ((NI) 1));				result = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_23);
#line 2188 "/usr/lib/nim/system.nim"
				nimln_(2188, "system.nim");				TM_CN3raB9atujkEiPpxYAdlgQ_24 = addInt(i_2, ((NI) 1));				i_2 = (NI)(TM_CN3raB9atujkEiPpxYAdlgQ_24);			} LA3: ;		}	}
#line 2421 "/usr/lib/nim/system.nim"
	nimln_(2421, "system.nim");	result = ((NI) -1);	}BeforeRet_: ;	popFrame();	return result;}


#line 2423 "/usr/lib/nim/system.nim"
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwterminal_extra)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;	NI T1_;	nimfr_("contains", "system.nim");{	result = (NIM_BOOL)0;
#line 2426 "/usr/lib/nim/system.nim"
	nimln_(2426, "system.nim");
#line 2426 "/usr/lib/nim/system.nim"

#line 2426 "/usr/lib/nim/system.nim"

#line 2426 "/usr/lib/nim/system.nim"
	T1_ = (NI)0;	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQterminal_extra(a, aLen_0, item);	result = (((NI) 0) <= T1_);	goto BeforeRet_;	}BeforeRet_: ;	popFrame();	return result;}


#line 835 "/usr/lib/nim/pure/terminal.nim"
N_LIB_PRIVATE N_NIMCALL(void, enableTrueColors_Gb9ag9a19a9c7zSn8N51nuAz4w)(void) {
	NimStringDesc* T1_;	NimStringDesc* T2_;	nimfr_("enableTrueColors", "terminal.nim");
#line 863 "/usr/lib/nim/pure/terminal.nim"
	nimln_(863, "terminal.nim");
#line 863 "/usr/lib/nim/pure/terminal.nim"

#line 863 "/usr/lib/nim/pure/terminal.nim"
	T1_ = (NimStringDesc*)0;	T1_ = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_28), ((NimStringDesc*) &TM_CN3raB9atujkEiPpxYAdlgQ_17));	T2_ = (NimStringDesc*)0;	T2_ = nsuToLowerAsciiStr(T1_);	trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw = contains_jPdUhZfr9a8sH2V3ZBDljzwterminal_extra(TM_CN3raB9atujkEiPpxYAdlgQ_25, 2, T2_);
#line 864 "/usr/lib/nim/pure/terminal.nim"
	nimln_(864, "terminal.nim");	trueColorIsEnabled_Y9c1UaDywi8o8DHl8VRJG9cQ = trueColorIsSupported_kn9b0UIbK9cVbUGz9cl7kNkkw;	popFrame();}
NIM_EXTERNC N_NOINLINE(void, stdlib_terminalInit000)(void) {
	nimfr_("terminal", "terminal.nim");	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_terminalDatInit000)(void) {
static TNimNode* TM_CN3raB9atujkEiPpxYAdlgQ_11[7];NI TM_CN3raB9atujkEiPpxYAdlgQ_13;static char* NIM_CONST TM_CN3raB9atujkEiPpxYAdlgQ_12[7] = {"styleBright", 
"styleDim", 
"styleUnknown", 
"styleUnderscore", 
"styleBlink", 
"styleReverse", 
"styleHidden"};static TNimNode TM_CN3raB9atujkEiPpxYAdlgQ_0[8];NTI_NXKayqTLMsAibFwNceBlpA_.size = sizeof(tyEnum_Style_NXKayqTLMsAibFwNceBlpA);NTI_NXKayqTLMsAibFwNceBlpA_.kind = 14;NTI_NXKayqTLMsAibFwNceBlpA_.base = 0;NTI_NXKayqTLMsAibFwNceBlpA_.flags = 3;for (TM_CN3raB9atujkEiPpxYAdlgQ_13 = 0; TM_CN3raB9atujkEiPpxYAdlgQ_13 < 7; TM_CN3raB9atujkEiPpxYAdlgQ_13++) {TM_CN3raB9atujkEiPpxYAdlgQ_0[TM_CN3raB9atujkEiPpxYAdlgQ_13+0].kind = 1;TM_CN3raB9atujkEiPpxYAdlgQ_0[TM_CN3raB9atujkEiPpxYAdlgQ_13+0].offset = TM_CN3raB9atujkEiPpxYAdlgQ_13;TM_CN3raB9atujkEiPpxYAdlgQ_0[TM_CN3raB9atujkEiPpxYAdlgQ_13+0].name = TM_CN3raB9atujkEiPpxYAdlgQ_12[TM_CN3raB9atujkEiPpxYAdlgQ_13];TM_CN3raB9atujkEiPpxYAdlgQ_11[TM_CN3raB9atujkEiPpxYAdlgQ_13] = &TM_CN3raB9atujkEiPpxYAdlgQ_0[TM_CN3raB9atujkEiPpxYAdlgQ_13+0];}TM_CN3raB9atujkEiPpxYAdlgQ_0[0].offset = 1;TM_CN3raB9atujkEiPpxYAdlgQ_0[1].offset = 2;TM_CN3raB9atujkEiPpxYAdlgQ_0[2].offset = 3;TM_CN3raB9atujkEiPpxYAdlgQ_0[3].offset = 4;TM_CN3raB9atujkEiPpxYAdlgQ_0[4].offset = 5;TM_CN3raB9atujkEiPpxYAdlgQ_0[5].offset = 7;TM_CN3raB9atujkEiPpxYAdlgQ_0[6].offset = 8;TM_CN3raB9atujkEiPpxYAdlgQ_0[7].len = 7; TM_CN3raB9atujkEiPpxYAdlgQ_0[7].kind = 2; TM_CN3raB9atujkEiPpxYAdlgQ_0[7].sons = &TM_CN3raB9atujkEiPpxYAdlgQ_11[0];NTI_NXKayqTLMsAibFwNceBlpA_.node = &TM_CN3raB9atujkEiPpxYAdlgQ_0[7];NTI_NXKayqTLMsAibFwNceBlpA_.flags = 1<<2;}

