/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:   gcc -c  -w -pthread -g3 -O0 -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/user/Dropbox/projects/nim/stui/nimcache/stdlib_cstrutils.o /home/user/Dropbox/projects/nim/stui/nimcache/stdlib_cstrutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix

#line 319 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 13 "/usr/lib/nim/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 16 "/usr/lib/nim/pure/cstrutils.nim"
static N_INLINE(NIM_CHAR, toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils)(NIM_CHAR c);
#line 30 "/usr/lib/nim/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
#line 12 "/usr/lib/nim/system/chcks.nim"
N_NOINLINE(void, raiseRangeError)(NI64 val);
#line 417 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 412 "/usr/lib/nim/system/excpt.nim"
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 70 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, popFrame)(void);
#line 326 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

#line 319 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 320 "/usr/lib/nim/system/arithm.nim"

#line 320 "/usr/lib/nim/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/usr/lib/nim/system/arithm.nim"
	{		NIM_BOOL T3_;
#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 321 "/usr/lib/nim/system/arithm.nim"

#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 321 "/usr/lib/nim/system/arithm.nim"

#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ b));		LA4_: ;		if (!T3_) goto LA5_;
#line 322 "/usr/lib/nim/system/arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 323 "/usr/lib/nim/system/arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 30 "/usr/lib/nim/system/chcks.nim"
static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;{	result = (NI)0;
#line 31 "/usr/lib/nim/system/chcks.nim"
	{		NIM_BOOL T3_;
#line 31 "/usr/lib/nim/system/chcks.nim"
		T3_ = (NIM_BOOL)0;
#line 31 "/usr/lib/nim/system/chcks.nim"
		T3_ = (a <= i);		if (!(T3_)) goto LA4_;
#line 31 "/usr/lib/nim/system/chcks.nim"
		T3_ = (i <= b);		LA4_: ;		if (!T3_) goto LA5_;
#line 32 "/usr/lib/nim/system/chcks.nim"

#line 32 "/usr/lib/nim/system/chcks.nim"
		result = i;		goto BeforeRet_;	}	goto LA1_;	LA5_: ;	{
#line 34 "/usr/lib/nim/system/chcks.nim"
		raiseRangeError(((NI64) (i)));	}	LA1_: ;	}BeforeRet_: ;	return result;}


#line 417 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
#line 418 "/usr/lib/nim/system/excpt.nim"
	T1_ = (NI)0;
#line 418 "/usr/lib/nim/system/excpt.nim"
	{
#line 418 "/usr/lib/nim/system/excpt.nim"
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;		T1_ = ((NI) 0);	}	goto LA2_;	LA4_: ;	{
#line 418 "/usr/lib/nim/system/excpt.nim"
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}	LA2_: ;	(*s).calldepth = ((NI16) (T1_));
#line 419 "/usr/lib/nim/system/excpt.nim"
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 420 "/usr/lib/nim/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 421 "/usr/lib/nim/system/excpt.nim"
	{
#line 421 "/usr/lib/nim/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
#line 421 "/usr/lib/nim/system/excpt.nim"
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();	}	LA9_: ;}


#line 70 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 71 "/usr/lib/nim/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}


#line 16 "/usr/lib/nim/pure/cstrutils.nim"
static N_INLINE(NIM_CHAR, toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils)(NIM_CHAR c) {
	NIM_CHAR result;	nimfr_("toLowerAscii", "cstrutils.nim");	result = (NIM_CHAR)0;
#line 17 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(17, "cstrutils.nim");	{		NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_4;
#line 17 "/usr/lib/nim/pure/cstrutils.nim"
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3_;
#line 18 "/usr/lib/nim/pure/cstrutils.nim"
		nimln_(18, "cstrutils.nim");
#line 18 "/usr/lib/nim/pure/cstrutils.nim"

#line 18 "/usr/lib/nim/pure/cstrutils.nim"

#line 18 "/usr/lib/nim/pure/cstrutils.nim"
		TM_is8NdSOqVDyl9a9bWX7JQtCQ_4 = addInt(((NU8)(c)), ((NI) 32));		result = ((NIM_CHAR) (((NI)chckRange((NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_4), ((NI) 0), ((NI) 255)))));	}	goto LA1_;	LA3_: ;	{
#line 20 "/usr/lib/nim/pure/cstrutils.nim"
		nimln_(20, "cstrutils.nim");		result = c;	}	LA1_: ;	popFrame();	return result;}


#line 326 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 327 "/usr/lib/nim/system/arithm.nim"

#line 327 "/usr/lib/nim/system/arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "/usr/lib/nim/system/arithm.nim"
	{		NIM_BOOL T3_;
#line 328 "/usr/lib/nim/system/arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 328 "/usr/lib/nim/system/arithm.nim"

#line 328 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 328 "/usr/lib/nim/system/arithm.nim"

#line 328 "/usr/lib/nim/system/arithm.nim"

#line 328 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4_: ;		if (!T3_) goto LA5_;
#line 329 "/usr/lib/nim/system/arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 330 "/usr/lib/nim/system/arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 46 "/usr/lib/nim/pure/cstrutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, csuCmpIgnoreStyle)(NCSTRING a, NCSTRING b) {
	NI result;	NI i;	NI j;	nimfr_("cmpIgnoreStyle", "cstrutils.nim");	result = (NI)0;
#line 54 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(54, "cstrutils.nim");	i = ((NI) 0);
#line 55 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(55, "cstrutils.nim");	j = ((NI) 0);	{
#line 56 "/usr/lib/nim/pure/cstrutils.nim"
		nimln_(56, "cstrutils.nim");		while (1) {			NIM_CHAR aa;			NIM_CHAR bb;			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_5;			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_6;			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_7;			{
#line 57 "/usr/lib/nim/pure/cstrutils.nim"
				nimln_(57, "cstrutils.nim");				while (1) {					NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_2;
#line 57 "/usr/lib/nim/pure/cstrutils.nim"
					if (!((NU8)(a[i]) == (NU8)(95))) goto LA4;
#line 57 "/usr/lib/nim/pure/cstrutils.nim"
					TM_is8NdSOqVDyl9a9bWX7JQtCQ_2 = addInt(i, ((NI) 1));					i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_2);				} LA4: ;			}			{
#line 58 "/usr/lib/nim/pure/cstrutils.nim"
				nimln_(58, "cstrutils.nim");				while (1) {					NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_3;
#line 58 "/usr/lib/nim/pure/cstrutils.nim"
					if (!((NU8)(b[j]) == (NU8)(95))) goto LA6;
#line 58 "/usr/lib/nim/pure/cstrutils.nim"
					TM_is8NdSOqVDyl9a9bWX7JQtCQ_3 = addInt(j, ((NI) 1));					j = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_3);				} LA6: ;			}
#line 59 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(59, "cstrutils.nim");			aa = toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils(a[i]);
#line 60 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(60, "cstrutils.nim");			bb = toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils(b[j]);
#line 61 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(61, "cstrutils.nim");
#line 61 "/usr/lib/nim/pure/cstrutils.nim"

#line 61 "/usr/lib/nim/pure/cstrutils.nim"

#line 61 "/usr/lib/nim/pure/cstrutils.nim"
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_5 = subInt(((NU8)(aa)), ((NU8)(bb)));			result = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_5);
#line 62 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(62, "cstrutils.nim");			{				NIM_BOOL T9_;
#line 62 "/usr/lib/nim/pure/cstrutils.nim"
				T9_ = (NIM_BOOL)0;
#line 398 "/usr/lib/nim/system.nim"
				nimln_(398, "system.nim");
#line 62 "/usr/lib/nim/pure/cstrutils.nim"
				nimln_(62, "cstrutils.nim");				T9_ = !((result == ((NI) 0)));				if (T9_) goto LA10_;
#line 62 "/usr/lib/nim/pure/cstrutils.nim"
				T9_ = ((NU8)(aa) == (NU8)(0));				LA10_: ;				if (!T9_) goto LA11_;
#line 62 "/usr/lib/nim/pure/cstrutils.nim"
				goto LA1;			}			LA11_: ;
#line 63 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(63, "cstrutils.nim");			TM_is8NdSOqVDyl9a9bWX7JQtCQ_6 = addInt(i, ((NI) 1));			i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_6);
#line 64 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(64, "cstrutils.nim");			TM_is8NdSOqVDyl9a9bWX7JQtCQ_7 = addInt(j, ((NI) 1));			j = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_7);		}	} LA1: ;	popFrame();	return result;}


#line 33 "/usr/lib/nim/pure/cstrutils.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, csuEndsWith)(NCSTRING s, NCSTRING suffix) {
	NIM_BOOL result;	NI slen;	NI i;	NI j;	NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_8;	nimfr_("endsWith", "cstrutils.nim");{	result = (NIM_BOOL)0;
#line 38 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(38, "cstrutils.nim");
#line 38 "/usr/lib/nim/pure/cstrutils.nim"
	slen = (s ? strlen(s) : 0);
#line 39 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(39, "cstrutils.nim");	i = ((NI) 0);
#line 40 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(40, "cstrutils.nim");
#line 40 "/usr/lib/nim/pure/cstrutils.nim"

#line 40 "/usr/lib/nim/pure/cstrutils.nim"
	TM_is8NdSOqVDyl9a9bWX7JQtCQ_8 = subInt(slen, (suffix ? strlen(suffix) : 0));	j = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_8);	{
#line 41 "/usr/lib/nim/pure/cstrutils.nim"
		nimln_(41, "cstrutils.nim");		while (1) {			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_9;			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_11;
#line 41 "/usr/lib/nim/pure/cstrutils.nim"

#line 41 "/usr/lib/nim/pure/cstrutils.nim"
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_9 = addInt(i, j);			if (!((NU64)((NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_9)) < (NU64)(slen))) goto LA2;
#line 42 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(42, "cstrutils.nim");			{				NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_10;
#line 398 "/usr/lib/nim/system.nim"
				nimln_(398, "system.nim");
#line 42 "/usr/lib/nim/pure/cstrutils.nim"
				nimln_(42, "cstrutils.nim");
#line 42 "/usr/lib/nim/pure/cstrutils.nim"
				TM_is8NdSOqVDyl9a9bWX7JQtCQ_10 = addInt(i, j);				if (!!(((NU8)(s[(NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_10)]) == (NU8)(suffix[i])))) goto LA5_;
#line 42 "/usr/lib/nim/pure/cstrutils.nim"

#line 42 "/usr/lib/nim/pure/cstrutils.nim"
				result = NIM_FALSE;				goto BeforeRet_;			}			LA5_: ;
#line 43 "/usr/lib/nim/pure/cstrutils.nim"
			nimln_(43, "cstrutils.nim");			TM_is8NdSOqVDyl9a9bWX7JQtCQ_11 = addInt(i, ((NI) 1));			i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_11);		} LA2: ;	}
#line 44 "/usr/lib/nim/pure/cstrutils.nim"
	nimln_(44, "cstrutils.nim");	{
#line 44 "/usr/lib/nim/pure/cstrutils.nim"
		if (!((NU8)(suffix[i]) == (NU8)(0))) goto LA9_;
#line 44 "/usr/lib/nim/pure/cstrutils.nim"

#line 44 "/usr/lib/nim/pure/cstrutils.nim"
		result = NIM_TRUE;		goto BeforeRet_;	}	LA9_: ;	}BeforeRet_: ;	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsInit000)(void) {
	nimfr_("cstrutils", "cstrutils.nim");	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsDatInit000)(void) {
}

