/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:   gcc -c  -w -pthread -g3 -O0 -O3 -fno-strict-aliasing  -I/usr/lib/nim -o /home/user/Dropbox/projects/nim/stui/nimcache/stdlib_cpuload.o /home/user/Dropbox/projects/nim/stui/nimcache/stdlib_cpuload.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA;typedef struct NimStringDesc NimStringDesc;typedef struct TGenericSeq TGenericSeq;typedef NU8 tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig;struct TGenericSeq {NI len;NI reserved;};
struct NimStringDesc {  TGenericSeq Sup;NIM_CHAR data[SEQ_DECL_SIZE];};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;struct tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA {NI calls;};

#line 348 "/usr/lib/nim/system/sysio.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, open_sEp0GH2306oGo9bqBpj5oTQ)(FILE** f, NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
#line 133 "/usr/lib/nim/system/sysio.nim"
N_LIB_PRIVATE N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
#line 44 "/usr/lib/nim/pure/concurrency/cpuinfo.nim"
N_LIB_PRIVATE N_NIMCALL(NI, ncpicountProcessors)(void);
#line 326 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b);
#line 13 "/usr/lib/nim/system/arithm.nim"
N_NOINLINE(void, raiseOverflow)(void);
#line 372 "/usr/lib/nim/system/arithm.nim"
N_NIMCALL(NI, mulInt)(NI a, NI b);
#line 319 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b);
#line 417 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s);
#line 412 "/usr/lib/nim/system/excpt.nim"
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 70 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, popFrame)(void);extern NIM_THREADVAR TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;STRING_LITERAL(TM_CFWzmO8DEHxStvjr8GyqGg_2, "/proc/loadavg", 13);

#line 326 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 327 "/usr/lib/nim/system/arithm.nim"

#line 327 "/usr/lib/nim/system/arithm.nim"
	result = (NI)((NU64)(a) - (NU64)(b));
#line 328 "/usr/lib/nim/system/arithm.nim"
	{		NIM_BOOL T3_;
#line 328 "/usr/lib/nim/system/arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 328 "/usr/lib/nim/system/arithm.nim"

#line 328 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 328 "/usr/lib/nim/system/arithm.nim"

#line 328 "/usr/lib/nim/system/arithm.nim"

#line 328 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));		LA4_: ;		if (!T3_) goto LA5_;
#line 329 "/usr/lib/nim/system/arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 330 "/usr/lib/nim/system/arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 319 "/usr/lib/nim/system/arithm.nim"
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;{	result = (NI)0;
#line 320 "/usr/lib/nim/system/arithm.nim"

#line 320 "/usr/lib/nim/system/arithm.nim"
	result = (NI)((NU64)(a) + (NU64)(b));
#line 321 "/usr/lib/nim/system/arithm.nim"
	{		NIM_BOOL T3_;
#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (NIM_BOOL)0;
#line 321 "/usr/lib/nim/system/arithm.nim"

#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ a));		if (T3_) goto LA4_;
#line 321 "/usr/lib/nim/system/arithm.nim"

#line 321 "/usr/lib/nim/system/arithm.nim"
		T3_ = (((NI) 0) <= (NI)(result ^ b));		LA4_: ;		if (!T3_) goto LA5_;
#line 322 "/usr/lib/nim/system/arithm.nim"
		goto BeforeRet_;	}	LA5_: ;
#line 323 "/usr/lib/nim/system/arithm.nim"
	raiseOverflow();	}BeforeRet_: ;	return result;}


#line 417 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
#line 418 "/usr/lib/nim/system/excpt.nim"
	T1_ = (NI)0;
#line 418 "/usr/lib/nim/system/excpt.nim"
	{
#line 418 "/usr/lib/nim/system/excpt.nim"
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;		T1_ = ((NI) 0);	}	goto LA2_;	LA4_: ;	{
#line 418 "/usr/lib/nim/system/excpt.nim"
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}	LA2_: ;	(*s).calldepth = ((NI16) (T1_));
#line 419 "/usr/lib/nim/system/excpt.nim"
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 420 "/usr/lib/nim/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 421 "/usr/lib/nim/system/excpt.nim"
	{
#line 421 "/usr/lib/nim/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
#line 421 "/usr/lib/nim/system/excpt.nim"
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();	}	LA9_: ;}


#line 70 "/usr/lib/nim/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 71 "/usr/lib/nim/system/excpt.nim"
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}


#line 31 "/usr/lib/nim/pure/concurrency/cpuload.nim"
N_LIB_PRIVATE N_NIMCALL(tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig, advice_uXlfLohkC9aBvpzhcIrG9amw)(tyObject_ThreadPoolState_jN9benzGjAA9bryIHC1FGnZA* s) {
	tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig result;	FILE* f;	NI TM_CFWzmO8DEHxStvjr8GyqGg_6;	nimfr_("advice", "cpuload.nim");	result = (tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig)0;	f = (FILE*)0;
#line 64 "/usr/lib/nim/pure/concurrency/cpuload.nim"
	nimln_(64, "cpuload.nim");	{		NIM_BOOL T3_;		NF b;		NI busy;		NI total;		NI cpus;
#line 64 "/usr/lib/nim/pure/concurrency/cpuload.nim"
		T3_ = (NIM_BOOL)0;		T3_ = open_sEp0GH2306oGo9bqBpj5oTQ(&f, ((NimStringDesc*) &TM_CFWzmO8DEHxStvjr8GyqGg_2), ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));		if (!T3_) goto LA4_;		b = (NF)0;		busy = (NI)0;		total = (NI)0;
#line 67 "/usr/lib/nim/pure/concurrency/cpuload.nim"
		nimln_(67, "cpuload.nim");		fscanf(f, "%lf %lf %lf %ld/%ld", (&b), (&b), (&b), (&busy), (&total));
#line 69 "/usr/lib/nim/pure/concurrency/cpuload.nim"
		nimln_(69, "cpuload.nim");		close_BWnr8V7RERYno9bIdPmw8Hw_2(f);
#line 70 "/usr/lib/nim/pure/concurrency/cpuload.nim"
		nimln_(70, "cpuload.nim");		cpus = ncpicountProcessors();
#line 71 "/usr/lib/nim/pure/concurrency/cpuload.nim"
		nimln_(71, "cpuload.nim");		{			NI TM_CFWzmO8DEHxStvjr8GyqGg_3;
#line 71 "/usr/lib/nim/pure/concurrency/cpuload.nim"

#line 71 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			TM_CFWzmO8DEHxStvjr8GyqGg_3 = subInt(busy, ((NI) 1));			if (!((NI)(TM_CFWzmO8DEHxStvjr8GyqGg_3) < cpus)) goto LA8_;
#line 72 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			nimln_(72, "cpuload.nim");			result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 1);		}		goto LA6_;		LA8_: ;		{			NI TM_CFWzmO8DEHxStvjr8GyqGg_4;			NI TM_CFWzmO8DEHxStvjr8GyqGg_5;
#line 73 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			nimln_(73, "cpuload.nim");
#line 73 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			TM_CFWzmO8DEHxStvjr8GyqGg_4 = mulInt(cpus, ((NI) 2));
#line 73 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			TM_CFWzmO8DEHxStvjr8GyqGg_5 = subInt(busy, ((NI) 1));			if (!((NI)(TM_CFWzmO8DEHxStvjr8GyqGg_4) <= (NI)(TM_CFWzmO8DEHxStvjr8GyqGg_5))) goto LA11_;
#line 74 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			nimln_(74, "cpuload.nim");			result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 2);		}		goto LA6_;		LA11_: ;		{
#line 76 "/usr/lib/nim/pure/concurrency/cpuload.nim"
			nimln_(76, "cpuload.nim");			result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0);		}		LA6_: ;	}	goto LA1_;	LA4_: ;	{
#line 78 "/usr/lib/nim/pure/concurrency/cpuload.nim"
		nimln_(78, "cpuload.nim");		result = ((tyEnum_ThreadPoolAdvice_vD9cAMuSmfH29a9al5Q9cUZCig) 0);	}	LA1_: ;
#line 82 "/usr/lib/nim/pure/concurrency/cpuload.nim"
	nimln_(82, "cpuload.nim");	TM_CFWzmO8DEHxStvjr8GyqGg_6 = addInt((*s).calls, ((NI) 1));	(*s).calls = (NI)(TM_CFWzmO8DEHxStvjr8GyqGg_6);	popFrame();	return result;}
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void) {
	nimfr_("cpuload", "cpuload.nim");	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void) {
}

